### ISSUE TITLE
Improve log levels

### ISSUE THREAD

**Issue by melkio** [Particular/NServiceBus.AzureStorageQueues#101]
Trying to identify why #86 issue happened, log was useless:
- when we don't have access to source code (nuget package referenced or working on customer code) understanding what's happening isn't easy. `Debug` level should log each method has been invoked, with parameters.
- here https://github.com/Particular/NServiceBus.AzureStorageQueues/blob/develop/src/Transport/MessagePump.cs#L199 log level is wrong (IMO): that's an error. Review all log levels.

Connects to https://github.com/Particular/NServiceBus.Azure/issues/309

**Comment by Scooletz** [comment]
@melkio As a step 0, we need to gather more info about what's an error/warning.

**Comment by melkio** [comment]
Sorry @Scooletz but I don't get your point. Isn't easy to discriminate an error from a warning?

Looking for a definition of log levels I found [this one](http://stackoverflow.com/questions/2031163/when-to-use-the-different-log-levels). It seems fine for me:
- **Trace**: only when I would be "tracing" the code and trying to find one part of a function specifically
- **Debug**: information that is diagnostically helpful to people more than just developers (IT, sysadmins, etc)
- **Info**: generally useful information to log (service start/stop, configuration assumptions, etc). Info I want to always have available but usually dont care about under normal circumstances. This is my out-of-the-box config level
- **Warn**: anything that can potentially cause application oddities, but for which I am automatically recoverring (such as switching from a primary to backup server, retrying an operation, missing secondary data, etc)
- **Error**: any error which is fatal to the operation but not the service or application (cant open a required file, missing data, etc). These errors will force user (administrator, or direct user) intervention. These are usually reserved (in my apps) for incorrect connection strings, missing services, etc.
- **Fatal**: any error that is forcing a shutdown of the service or application to prevent data loss (or further data loss). I reserve these only for the most heinous errors and situations where there is guaranteed to have been data corruption or loss.

f.i. if transport isn't able to push messages to core because a deserialization issue (or something similar), is an error.

**Comment by SeanFeldman** [comment]
@melkio I think the intent was to determine what _constitutes_ an error to be considered as an error vs a warning. For example: account being throttled exception, that's a warning. Unless all retries are exhausted, then it becomes an error.

**Comment by Scooletz** [comment]
@melkio , @SeanFeldman described what exactly what I had in mind.

**Comment by melkio** [comment]
@SeanFeldman I understood, but isn't it clear? Do linked definitions cover your doubts?

> Warn: anything that can potentially cause application oddities, but for which I am automatically recoverring
> Error: any error which is fatal to the operation but not the service or application

**Comment by SeanFeldman** [comment]
@melkio those definitions are great. I was just voicing out what @Scooletz said - we shouldn't make assumptions and look at each scenario case by case :)

**Comment by SeanFeldman** [comment]
Recently, I've had a support case where it was impossible to identify why ASQ was failing from the logs. The issue was the failure to deserialize message wrapper on a message that was not constructed by NServiceBus. It would be worth adding those types of logs.
