### ISSUE TITLE
Endpoint shuts down and triggers critical error while acknowledging   a message that has failed and exceeded the visibility timeout

### ISSUE THREAD

**Issue by danielmarbach** [Particular/NServiceBus.AzureStorageQueues#1077]
Related to https://github.com/Particular/NServiceBus.AzureStorageQueues/issues/1076

### Symptoms

When a handler runs longer than the timeout value, the message is requeued by the broker and the transport logs a [warning](https://github.com/Particular/NServiceBus.AzureStorageQueues/blob/master/src/Transport/MessageReceiver.cs#L209) but is unable to ACK the message due to the timeout. When this happens, the circuit breaker will be triggered and the message will be retried (retriggering the circuit breaker) until the handler completes quicker than the timeout. No configured recoverability policies will apply and the critical error action will be raised.

### Who's affected

Affected are used who either:
 - Have message handlers that take long (by default more than [30 seconds](https://docs.particular.net/transports/azure-storage-queues/configuration#configuration-parameters-messageinvisibletime)) to execute. These messages undergo numerous retry attempts that trigger the circuit breaker unless subsequent executions (after the first one) take less time. Customers who use the Outbox  **are not** affected because the second attempt bypasses the handler execution
 - Have messages that fail due to a persistent issue (e.g. bug in code) and the handler execution time before the exception is raised multiplied by the number of immediate retries is higher than [30 seconds](https://docs.particular.net/transports/azure-storage-queues/configuration#configuration-parameters-messageinvisibletime). 

### Workaround

A temporary workaround for the issue, if you are affected, is to extend the [message visibility timeout](https://docs.particular.net/transports/azure-storage-queues/configuration#configuration-parameters-messageinvisibletime) value.

**Comment by danielmarbach** [comment]
We've prioritized your issue near the top of our list and will work on it as soon as we can.

**Comment by TravisNickels** [comment]
This has been fixed by:
- https://github.com/Particular/NServiceBus.AzureStorageQueues/pull/1212

With backports:
- version 10.0.6 - https://github.com/Particular/NServiceBus.AzureStorageQueues/pull/1220
- version 12.0.2 - https://github.com/Particular/NServiceBus.AzureStorageQueues/pull/1215
- version 13.0.1 - https://github.com/Particular/NServiceBus.AzureStorageQueues/pull/1214
