### ISSUE TITLE
Align namespaces in the project

### ISSUE THREAD

**Issue by Scooletz** [Particular/NServiceBus.AzureStorageQueues#110]
Currently, there are following namespaces in the project:
- [x] `NServiceBus` - containing only public API
- [x] `NServiceBus.Azure.Transports.WindowsAzureStorageQueues` - only `[ObsoleteEx]`
- [ ] `NServiceBus.AzureStorageQueues` - internal types to be moved to `NServiceBus.Transports.AzureStorageQueues`
- [ ] `NServiceBus.AzureStorageQueues.Config` - internal types to be moved to `NServiceBus.Transports.AzureStorageQueues`
- [x] `NServiceBus.Config` - only `[ObsoleteEx]`
- [x] `NServiceBus.Features` - only `[ObsoleteEx]`
- [ ] `TaskEx`  to be moved to `NServiceBus.Transports.AzureStorageQueues`

**Comment by SeanFeldman** [comment]
Requires verification prior to us doing anything.
