### ISSUE TITLE
ServiceControl support for multiple accounts

### ISSUE THREAD

**Issue by Scooletz** [Particular/NServiceBus.AzureStorageQueues#116]
In the version 6 of Azure Storage Transport it's been possible to send messages to another account using `queueName@storageAccount` address. How does it work with `ServiceControl`? What about scenarios where `audit` and/or `error` queues were moved to another account because of the scalability purposes?
Having examples representing meaningful scenarios for this would be beneficial to ensure that ASQ v7 works properly with SC.

/cc @timbussmann @melkio

**Comment by SeanFeldman** [comment]
@Particular/azure-storage-queues-maintainers this is not unique to ASQ only. ASB had the same option in V6. 
Multiple accounts would require multiple SC instances in ASQ v6.
I suggest we discuss this during our sync with @Particular/azure-service-bus-maintainers

**Comment by dvdstelt** [comment]
Is this sync today? I have a day off, so if it's today, please share the outcome here?

**Comment by timbussmann** [comment]
can you verify the documentation http://docs.particular.net/nservicebus/azure-service-bus/multiple-namespaces-support contains the required information about using SC in such scenarios?

**Comment by SeanFeldman** [comment]
@timbussmann why would a transport doxument contain documentation about special case setup for SC? This is not unique to ASB or ASQ. Therefore perhaps should be under SC doco.

**Comment by Scooletz** [comment]
@WojcikMike did an amazing job in finding all the rules, headers etc and gathering them in one post. Should we raise an issue for ServiceControl? It's a very good material but, covering it in docs can be a scope creep for our current work imo.

**Comment by Scooletz** [comment]
I'm leaving this discussion open, but unpinning from the beta scope.

**Comment by SeanFeldman** [comment]
This is going to be addressed by the Launch Wave with SC adapters. Closing.
