### ISSUE TITLE
ASQ doesn't work with XML MessageWrappers

### ISSUE THREAD

**Issue by timbussmann** [Particular/NServiceBus.AzureStorageQueues#124]
When configuring the acceptance tests to work with the XmlSerializer (`.UseSerializer<XmlSerializer>()`) the `MessageWrapper` class won't be properly deserialized which makes the endpoint unable to receive messages.

It seems like the internal `XmlSerializerCache` isn't initialized with the `MessageWrapper` class. On endpoints which send messages this seems to work after they send a message since the serialization logic does add missing types to the cache.

@Particular/azure-storage-queues-maintainers ping. This seems to be must-have before the RC.

**Comment by timbussmann** [comment]
note: I think we maybe need to handle this in the XmlSerializer. The serialization logic does initialize the type at runtime if it's missing in the cache while deserialization does not. We could adjust that behavior to also initialize types at runtime if they seem missing. /cc @Particular/nservicebus-maintainers

**Comment by Scooletz** [comment]
It's highly unlikely that anyone is using XML instead of JSON, but as we provide a way to configure it, we should be handling it right. I'm looking forward to hearing from @Particular/nservicebus-maintainers if this is going to be handled in the core and ASQ will just bump up the version of the core.

**Comment by timbussmann** [comment]
@Particular/nservicebus-maintainers @Particular/azure-storage-queues-maintainers I think I found a minimal invasive solution by sneaking in this config somewhere on the ASQ setup:
`settings.Get<Conventions>().AddSystemMessagesConventions(t => t == typeof(MessageWrapper));`

this is the simplest way of getting `MessageWrapper` being accepted as a message type which will also initialize it properly (it was skipped because it's from a particular assembly and we would exclude messages from particular assemblies). Will test whether that works and raise a PR if it does.

**Comment by Scooletz** [comment]
Would be more than happy to review & accept it :)

**Comment by timbussmann** [comment]
should be fixed with #125
