### ISSUE TITLE
Message deletion behaviour is not consistent

### ISSUE THREAD

**Issue by SeanFeldman** [Particular/NServiceBus.AzureStorageQueues#126]
## Who's affected

- Any ASQ users that run with a single consumer (with concurrency of 1) and later either scaling out or increasing concurrency level.

## Symptoms

- With a single consumer, message can be deleted after `VisibilityTimeout` elapses. With multiple consumers, this is not going to be possible.

## Analysis

This is an issue with the MSFT ASQ library design. It provided a pop receipt for a message w/o connecting it to visibility timeout. I have [reported the issue](https://github.com/Azure/azure-storage-net/issues/285) and it's now a feature request. 

A possible workaround is to correlate between time when message was received and attempted for deletion [suggested by the ASQ team](https://github.com/Azure/azure-storage-net/issues/285#issuecomment-223887791).

**Comment by SeanFeldman** [comment]
Discussed the issue with @dbelcham and @Scooletz.

The workaround from the conversation with MSFT Storage team would be to stamp an incoming message with a client side date/time. Upon removal, validate the that invisibility time has not elapsed according to the stamp on the message, rather than relying on the pop receipt.

**Comment by Scooletz** [comment]
Fixed by  #138

**Comment by andreasohlund** [comment]
Is this a bug that is present in previous versions or is this a v7 pre-release bug?

**Comment by Scooletz** [comment]
@andreasohlund This is Azure Storage Queues service bug as this service does not invalidate an expired pop receipt. This can be observed only in long running handlers of scaled out endpoints. So if the question is, 'is it present in previous versions?', yet it is as it's an Azure Storage Queue bug. We're just patching it on our end.

**Comment by andreasohlund** [comment]
In that case should we add this to the 7.0.0 milestone?

**Comment by Scooletz** [comment]
@andreasohlund Done.
