### ISSUE TITLE
High storage costs in default mode

### ISSUE THREAD

**Issue by andreasohlund** [Particular/NServiceBus.AzureStorageQueues#139]
When running 2 endpoints in idle mode (no messages processed), we get around 50 million storage requests per day per endpoint

![asq-cost](https://cloud.githubusercontent.com/assets/125028/17481939/be3a8af8-5d7f-11e6-85a0-19e133865c1c.PNG)

After changing  the settings to:

```

           configuration.UseTransport<AzureStorageQueueTransport>()
                .DegreeOfReceiveParallelism(1)
                .MaximumWaitTimeWhenIdle(TimeSpan.FromSeconds(1))
                .PeekInterval(TimeSpan.FromSeconds(1))
```

The number of calls go down as you see in the graph.

This seems like to much cost for 2 idle endpoints?

Shouldn't the transport dial back on the polling automatically if there is no messages coming in?

**Comment by andreasohlund** [comment]
Ping  @Particular/azure-storage-queues-maintainers @yvesgoeleven @danielmarbach

**Comment by Scooletz** [comment]
Thx @andreasohlund for reporting it. I've checked it and it seems that's it is a bug. The receive loop should not reset counter every time. It looks that is has been introduced in [here](https://github.com/Particular/NServiceBus.AzureStorageQueues/commit/176826d7e2c59421a7c0ac6ffcde4513a3e34349#diff-77c94d8919955df30fcbbd39e06f7ca1L72)

I'll handle it. Any other @Particular/azure-storage-queues-maintainers to confirm?

**Comment by danielmarbach** [comment]
Interesting. If I recall correctly I haven't changed that part the PR in question did only move around code. @scooletz happy to learn from my mistake. Ping me tomorrow

**Comment by danielmarbach** [comment]
When I recall the discussion correctly we made an explicit choice and tunes the defaults for max throughput (square root of concurrency limit of core) and added a caveat (info box) section to http://docs.particular.net/nservicebus/azure-storage-queues/performance-tuning
We also decided against any backtracking / dial down behavior. Happy to start the discussion again

**Comment by danielmarbach** [comment]
See also http://docs.particular.net/nservicebus/azure-storage-queues/configuration

**Comment by danielmarbach** [comment]
According to Azure procing 1.7 million requests would cost you 6 cents a day. 0.0036 USD per 100k tx. We are speaking of 1 USD per endpoint per month with the defaults tuned for perf

**Comment by andreasohlund** [comment]
Can't we dial back on the parallell receivers when there is no message for X? (and then dial them up when a message arrives)

Also something is off with the calculation, for me 2 endpoints costed 147 sek (17 USD) for 25 days?

**Comment by yvesgoeleven** [comment]
The transports should dial back, a cost like this for an idle endpoint will be a turn off for any trial user

**Comment by yvesgoeleven** [comment]
imagine you install a few samples application, and than have to pay 8 USD for each, this will quickly add up, lock trial account and be unhappy. @andreasohlund 's reaction is completely normal

**Comment by Scooletz** [comment]
It is a bug, not a wrong approach taken. Let's focus on fixing the bug. The approach we took with multiple loops is still ok.

@danielmarbach @andreasohlund The PR #140 shows what was missing and why the `timeToDelayNextPeek` was always being set to 0 after the delay (which was wrong).

**Comment by andreasohlund** [comment]
The calculation was off, doing it again together with @danielmarbach @mikeminutillo and @SzymonPobiega we concluded (and it matched with the actuall billing) that each idle endpoint will perform 50 million storage requests per day, roughly 0.5 USD per day => 15 USD per month

**Comment by Scooletz** [comment]
@andreasohlund Still, imo, there's a bug that is addressed by the PR mentioned above.

**Comment by danielmarbach** [comment]
Currently the default peek interval is 50 ms and the default batch size 32. That brings us to 33 storage queue ops every 50 ms seconds and then of those in parallel. Assuming the endpoint would only have on receiver this brings us up to

20 x 33 x 10 = 6600 ops / s

the default limit per storage queue is 2000 ops / s

how about we tweak the default peek interval to 125 ms

which would mean

8 x 33 x 10 = 2640 ops / s

Of course the trade off would be that when messages are slowly arriving into the almost empty queue the latency would be 2.5 times higher than with 50 ms. But maybe that is neglectable since we retrieve in batches? Arguably users can always tweak these defaults. Thoughts?

**Comment by Scooletz** [comment]
@yvesgoeleven Thoughts on this :point_up:

**Comment by Scooletz** [comment]
I'm removing the labels from this and mark the PR with them. This looks like a discussion to me right now.

**Comment by yvesgoeleven** [comment]
We used to dial back to 1 request per 30 seconds.... nobody every complained about that

**Comment by yvesgoeleven** [comment]
latency on first message in an empty queue really isn't that important, as long as it speeds up when more messages come in

**Comment by Scooletz** [comment]
@andreasohlund @danielmarbach Should we close this as #141 will increase the default value?

**Comment by andreasohlund** [comment]
I'm :+1: to close

**Comment by yvesgoeleven** [comment]
Ok to close, but I would also reduce the concurrency value, if you already pull in batches it's probably not needed to pull so many batches concurrently?

**Comment by Scooletz** [comment]
Could you elaborate @yvesgoeleven ? The number of retrieving loops is based on the concurrency. It's overridable as well. I wouldn't change the algorithm as it works good in a saturated environment (more loops calling `GetMessages` - better throughput).

**Comment by yvesgoeleven** [comment]
2640 ops / s per endpoint is extremely aggressive, remember that you have to multiply this by the number of endpoints in a solution

**Comment by yvesgoeleven** [comment]
compared to the previous 1 per 30 seconds...

**Comment by danielmarbach** [comment]
That can be mitigated by changing the default wait time when idle to 30 seconds.

**Comment by yvesgoeleven** [comment]
👍 That would indeed be a better change!

**Comment by danielmarbach** [comment]
@Scooletz :arrow_up: thoughts?

**Comment by andreasohlund** [comment]
30 seems high, isn't 5s or 10s more reasonable? (waiting 30s when debugging is a loooong time)

**Comment by yvesgoeleven** [comment]
@andreasohlund it's not 0 to 30, it should increment progressively (PeekInterval increments), up to 30 and reset on a message. So startup = immediate read (you probably debug this one), when message continue immediate... when no message add some milliseconds, again no message wait 2x that, then 3x, etc.. repeat until maxed at 30 secs. Whenever a message comes in, reset the counter

**Comment by andreasohlund** [comment]
ah, got it

**Comment by Scooletz** [comment]
@danielmarbach @yvesgoeleven My thoughts are: :+1: 
I'm changing the pull request.

**Comment by Scooletz** [comment]
Done in https://github.com/Particular/NServiceBus.AzureStorageQueues/pull/141/commits/7894da20d6181ab3666648a1864e9113b8e30f01
