### ISSUE TITLE
Messages seems to be processed in parallel even though concurrency = 1

### ISSUE THREAD

**Issue by andreasohlund** [Particular/NServiceBus.AzureStorageQueues#154]
I have a saga that receives 5-6 messages that will hit the same saga. The saga persister correctly rollback with a concurrency exception. This happens with:

`.DegreeOfReceiveParallelism(1)`

I would expect the messages to be processed sequentially?

This is on the latest RC bits

**Comment by Scooletz** [comment]
Setting 'DegreeOfReceiveParallelism' to 1 means that there's only one loop retrieving messages. It does not limit the concurrency though, which by default is higher than 1 (I can't remember the latest setting for the core). This enables executing multiple messages at the same time using one retrieving loop.

To limit both, the `DegreeOfReceiveParallelism` and `MaxConcurrency` you can set the concurrency to 1 which will affect the 'DegreeOfReceiveParallelism` as well or set these two values explicitly.

**Comment by andreasohlund** [comment]
My bad, I mixed up the 2 settings :)           

>  configuration.LimitMessageProcessingConcurrencyTo(1);

get the job done!
