### ISSUE TITLE
Unable to get pub sub working on Azure

### ISSUE THREAD

**Issue by Rommel-Villa** [Particular/NServiceBus.AzureStorageQueues#16]
We have an application running in a VM in azure as a publisher, and have a subscriber running in a worker role. We cannot get pub sub working between both in azure. At one point I had a test subscriber application that worked under 4.x but it no longer works with the latest NSB and storage updates, but it can register with the publisher. 

We went back to a older demo where pub sub worked, we updated it to the latest version, NSB, storage etc, and it no longer works. Not sure if it's the same issue. 

https://github.com/Rommel-Villa/NSB_Spike

Current Version
NserviceBus 5.2.4
NServiceBus Azure 6.2.1
NServiceBus.Azure.Transports.WindowsAzureStorageQueues 6.2.1
Windows Azure Storage 4.3.0

**Comment by SeanFeldman** [comment]
Resolved. Issue with assembly versioning.
