### ISSUE TITLE
Align/bump up versions of dependencies

### ISSUE THREAD

**Issue by Scooletz** [Particular/NServiceBus.AzureStorageQueues#162]
Align version of the testing libraries across all the test projects.
Bump up the storage library.
Review the dependencies (`Mono.Cecil` and others). Maybe some are unneeded.

**Comment by SeanFeldman** [comment]
Not sure I fully understand this issue. Is there a specific action or this is a placeholder?

**Comment by Scooletz** [comment]
It looked like a placeholder, but now I changed the description. I saw a few projects using different versions of acceptance tests. We can bump them up and review dependencies at the same time.

**Comment by Scooletz** [comment]
Solved by https://github.com/Particular/NServiceBus.AzureStorageQueues/pull/163
