### ISSUE TITLE
Document Native Delayed Delivery

### ISSUE THREAD

**Issue by Scooletz** [Particular/NServiceBus.AzureStorageQueues#166]
Connects to https://github.com/Particular/NServiceBus.AzureStorageQueues/issues/235

Document `Native Delayed Delivery` introduced and stabilized in these PRS #161, #165.

Follow the guides provided by @dvdstelt in this comment https://github.com/Particular/NServiceBus.AzureStorageQueues/pull/165#issuecomment-255341807 taking into account the need of maintenance/dev-ops perspective.

> It means that both developers and operations team need to have knowledge of the fact that precious business data is running in Azure Table Storage, not just in queues and wherever-the-business-data-is-persisted. And that they need to support it. I'm serious, that's no small issue! And we as Particular Software need to support several implementations of this native delivery (ASQ, RabbitMQ, SQL) and also support needs to be made aware of the changes/updates and be aware of the fact that timeouts live there. Which isn't documented anywhere but in a TON of GH issues.

**Comment by dvdstelt** [comment]
The last part about documentation, I was more referring to technical documentation, which isn't available at the moment. [Hopefully it will at some point in time](https://github.com/Particular/PlatformDevelopment/issues/862). Of course it should also be in end-user documentation.

**Comment by Scooletz** [comment]
I think that we can't cover the technical doco right now as there's no frame for it. We can provide a good end-user doco though, describing some technical aspects as well.

**Comment by SeanFeldman** [comment]
Closing. [Doco already exists](https://docs.particular.net/transports/azure-storage-queues/delayed-delivery).
