### ISSUE TITLE
List approaches we can take to migrage from AzureStorage based timeouts to Native Delayed Delivery

### ISSUE THREAD

**Issue by Scooletz** [Particular/NServiceBus.AzureStorageQueues#167]
Connects to https://github.com/Particular/NServiceBus.AzureStorageQueues/issues/235

/cc @SeanFeldman

**Comment by SeanFeldman** [comment]
Would state that first is to list the options (migration tool, run-time migration, etc) and then decide with @Particular/azure-storage-queues-maintainers what's the best approach to take.

**Comment by Scooletz** [comment]
Sure @SeanFeldman I've updated the title.

**Comment by SeanFeldman** [comment]
This is addressed by ASQ.
Ability to [run in a "hybrid mode"](https://docs.particular.net/transports/azure-storage-queues/delayed-delivery#backwards-compatibility) removed the need to migrate per-se.
