### ISSUE TITLE
There should be a Native Integration example

### ISSUE THREAD

**Issue by dbelcham** [Particular/NServiceBus.AzureStorageQueues#169]
Currently there is no sample code or documentation page that outlines what you need to do to have native integration with ASQ.

**Comment by Scooletz** [comment]
There's a sample providing a way of displaying/consuming messages, [the reader](https://github.com/Particular/docs.particular.net/tree/master/samples/azure/storage-queues/ASQ_7/StorageReader). but I presume you mean the sending part as well. Something similar to the ASB Native Integration, right?

**Comment by SeanFeldman** [comment]
@Scooletz correct

**Comment by Scooletz** [comment]
We could provide a sample how to send messages, on the other hand we should take into consideration #160 which enables handling `native messages` in a more graceful way. In my opinion, if we accept this PR, we need to document both: 
- an endpoint handling native messages 
- sending messages in a format consumed by a regular endpoint

**Comment by SeanFeldman** [comment]
👍 for PR #160 first and documenting native integration based on it.

Which begs a question why to bother with a "native" sample that uses message envelop enforced by NSB.ASQ? That would not really be a native integration anymore since native senders wouldn't care about the wrapper.

**Comment by Scooletz** [comment]
With #160 you can have one or another - you can't have an endpoint that accepts both unless you provide a method for that. If we provided a sample with this hybrid function, we could stick to one example though.

**Comment by Scooletz** [comment]
With #160 you can have one or another - you can't have an endpoint that accepts both unless you provide a method for that. If we provided a sample with this hybrid function, we could stick to one example though.

**Comment by SeanFeldman** [comment]
A PlatDev issue should replace this one.

**Comment by danielmarbach** [comment]
Raised https://github.com/Particular/PlatformDevelopment/issues/1553. Closing
