### ISSUE TITLE
ASQ should handle different formats for connection strings

### ISSUE THREAD

**Issue by Scooletz** [Particular/NServiceBus.AzureStorageQueues#171]
The same connection string can have different forms depending on the fact whether the `blobs`, `files` or the account key (`Primary` or `Secondary`) is used. This, when multiple forms of the same connection string are used, will blow up the mapping.
Different tools, can return different forms of this making it even more important to handle.

The proposal is to extract the `accountName` and use that as a connection string key.

/cc @andreasohlund

**Comment by yvesgoeleven** [comment]
@andreasohlund Are these formats related to limited storage access, as in shared access signatures to specific resources? If so how can we ensure that account name will map to another connection string that has sufficient rights to perform the requested operation?

**Comment by andreasohlund** [comment]
In my case I just copy pasted the string from 2 different tools (SC used one format and my endpoint the other)

The diff was the  "endpoints" part and that caused my endpoint to go into an infinite "put the message back into the queue" loop. In my case the rest of the connection string was identical?

**Comment by Scooletz** [comment]
Did endpoint log the error properly? In other words, were you able to figure it out without having the access to ASQ code? @andreasohlund

**Comment by andreasohlund** [comment]
No the endpoint went into an endless retry loop , I noticed that there was messages that where constantly failing by coincidence by looking at the number of invisible messages using Storage Explorer

**Comment by SeanFeldman** [comment]
Are we over complicating this a bit? We could clearly state that "for ASQ to function properly, it requires an account connection string ". Not a specific service connection string. Especially knowing about potential usage other services than just queues for future features (timeouts).

**Comment by boblangley** [comment]
Instead should we be guiding our users to dedicate a storage account for messaging and not using it for other concerns as well?

**Comment by Scooletz** [comment]
Being given what @boblangley is this a documentation issue only then? As I mentioned before, if we introduced the check for format, it would be breaking change. On the other side, maybe it's worth to make this breaking change? @Particular/azure-maintainers  ?

**Comment by SeanFeldman** [comment]
I tend to agree with @boblangley. It's a guidance issue. When using MSMQ, you're expected to have the space for your messages and machine with appropriate IOPS. Same with the storage account, dedicate one for messaging, don't reuse the same account for multiple things and expect to connect with various connection strings.

**Comment by Scooletz** [comment]
Based on your opinions @boblangley @SeanFeldman I removed the `bug` label. How would we like to tackle it then?

**Comment by SeanFeldman** [comment]
Doco update/clarification?

**Comment by SeanFeldman** [comment]
Should be handled by the Storage client in a transparent way.
Saying that, we need to verify it's working properly.

**Comment by yvesgoeleven** [comment]
Tested, works now
