### ISSUE TITLE
TimeoutEntity questions

### ISSUE THREAD

**Issue by SimonCropp** [Particular/NServiceBus.AzureStorageQueues#178]
```
    class TimeoutEntity : TableEntity
    {
        public string Destination { get; set; }
        public byte[] Body { get; set; }
        public string MessageId { get; set; }
        public string Headers { get; set; }
        
        static string Serialize<T>(T obj)
        {
            var sw = new StringWriter();
            new JsonSerializer().Serialize(sw, obj);
            sw.Flush();
            return sw.ToString();
        }

        static T Deserialize<T>(string obj)
        {
            return new JsonSerializer().Deserialize<T>(new JsonTextReader(new StringReader(obj)));
        }
```

 * `new JsonSerializer()` is an expensive operation. and this is on the fast path? So i assume JsonSerializer should be cached?
 * if we explicitly use json .net (ie not an inferred nuget dependency) then it needs to be a nuget dependency in our spec. if we dont, changes in upstream packages in the future could result in no json .net referenced
 * why are we using disposbale stuff and not putting them in a using

**Comment by Scooletz** [comment]
Why is this not a PR @SimonCropp ? :P 
Let me handle it either tomorrow or next week.

**Comment by SimonCropp** [comment]
@Scooletz happy to do a PR. I am not familiar with the codebase. so i just wanted to make sure there was nothing i was missing

**Comment by danielmarbach** [comment]
Storage persistence has similar problems. I'll send in PRs
