### ISSUE TITLE
Release 7.1

### ISSUE THREAD

**Issue by Scooletz** [Particular/NServiceBus.AzureStorageQueues#187]
PoA:
- [x] Bump up the storage library to 8.* https://www.nuget.org/packages/WindowsAzure.Storage/
- [x] mark PRs/issues with the milestone
- [x] create `release-7.1`
- [x] release RC to myget
- [x] smoke test 
- [x] merge to master and release to myget
- [x] move to ASP to bump up to myget version
- [x] bump up docs (https://github.com/Particular/docs.particular.net/pull/2504)
- [x] ~Prepare `hotfix-7.1.1` widening the nuspec range~
- [x] Prepare `7.2` fixing dependencies
- [x] release in cohort with other Azure libs (`7.2` first, then `7.1`)
- [x] release an announcement that informs about `7.1` and `7.2` in one message

**Comment by SeanFeldman** [comment]
>  create release-7.0

did you mean `support-7.0` or `release-7.1`? Need both :)

**Comment by SeanFeldman** [comment]
Released
