### ISSUE TITLE
Should log if exception occurred during send operation

### ISSUE THREAD

**Issue by SeanFeldman** [Particular/NServiceBus.AzureStorageQueues#19]
When ASQ message is sent out, we should log (FATAL) an exception if send is failing similar to [ASB](https://github.com/Particular/NServiceBus.AzureServiceBus/blob/113dbf9ced02eac6935353d71000402eaf54ab60/src/Transport/Sending/SendResourceManager.cs).

**Comment by yvesgoeleven** [comment]
With core v6 not using scopes anymore, I think this one will be covered automatically

**Comment by Scooletz** [comment]
Current implementation does not wrap dispatching messages in any kind of logging. `ImmediateDispatchTerminator` is the behavior/stage connector responsible for sending. If it throws, exception propagate through the pipeline
```
await pipeline(pushContext).ConfigureAwait(false);
```

finally being handled by in ASQ by
```
catch (Exception ex)
{
    // (...)
    Logger.Warn("Azure Storage Queue transport failed pushing a message through pipeline", ex);
}
```
Sending related errors will be logged with WARN as well. Should we treat them as FATAL? There's not that much FATAL errors logged in NSB.

**Comment by SeanFeldman** [comment]
"failed pushing a message through pipeline" or "failed to dispatch a message"?
I see those as two different things.

**Comment by Scooletz** [comment]
Valid point. That's message is from the previous version. What I can propose is to properly wrap dispatching, throwing a special exception which will have that notion. I can cover it with an acceptance test.
Anyway, I'm reading your response as "yes AND..." :)

**Comment by SeanFeldman** [comment]
:+1:
