### ISSUE TITLE
Documentation for operational scripting for ASQ

### ISSUE THREAD

**Issue by SeanFeldman** [Particular/NServiceBus.AzureStorageQueues#204]
<sup>*Moved from https://github.com/Particular/docs.particular.net/issues/1256 opened by @yvesgoeleven on [07 Mar 2016 09:34 UTC](https://github.com/Particular/docs.particular.net/issues/1256)*</sup>
Similar to
- [RabbitMQ](http://docs.particular.net/nservicebus/rabbitmq/operations-scripting)
- [SQL](http://docs.particular.net/nservicebus/sqlserver/operations-scripting)
- [MSMQ](http://docs.particular.net/nservicebus/msmq/operations-scripting)

to complete the [native integration sample](https://github.com/Particular/docs.particular.net/issues/887)

Connects to https://github.com/Particular/NServiceBus.Azure/issues/310

**Comment by SeanFeldman** [comment]
<sup>*@SimonCropp commented on <a id="issuecomment-194564807" href="204#user-content-issuecomment-194564807">09 Mar 2016 23:30 UTC</a>*</sup>
@yvesgoeleven since we dont currently have any operational scripting for azure i dont think this should have a v6 label


---
<sup>*@Scooletz commented on <a id="issuecomment-213449678" href="204#user-content-issuecomment-213449678">22 Apr 2016 14:30 UTC</a>*</sup>
@yvesgoeleven Could you clarify this issue? In my opinion it's not needed for beta of ASQ.


---
<sup>*@yvesgoeleven commented on <a id="issuecomment-214243455" href="204#user-content-issuecomment-214243455">25 Apr 2016 10:02 UTC</a>*</sup>
@Scooletz this is indeed not needed for beta and can be done later. The intent is to have similar doco like the transports mentioned where we show how to do native integration as well as powershell scripts to set up the queues as part of an installation script


---
<sup>*@SeanFeldman commented on <a id="issuecomment-284491515" href="204#user-content-issuecomment-284491515">06 Mar 2017 18:45 UTC</a>*</sup>
Suggested approach to take is similar to [ASB](https://docs.particular.net/nservicebus/azure-service-bus/operational-scripting).
- [.NET API](https://docs.microsoft.com/en-us/azure/storage/storage-dotnet-how-to-use-queues)
- [REST API](https://docs.microsoft.com/en-us/rest/api/storageservices/fileservices/queue-service-rest-api)
etc

**Comment by SeanFeldman** [comment]
We could refer customers to Azure CLI: https://docs.microsoft.com/en-us/cli/azure/storage/queue?view=azure-cli-latest in the documentation.

**Comment by soujay** [comment]
@SeanFeldman - Thank you for the suggestion to add in the operational scripting for ASQ. We have added the [operational scripting](https://docs.particular.net/transports/azure-storage-queues/operations-scripting) page on the docs website
