### ISSUE TITLE
Support JSON.Net 10.x

### ISSUE THREAD

**Issue by gbiellem** [Particular/NServiceBus.AzureStorageQueues#209]
NServiceBus.Newtonsoft.Json supports JSON.Net 10.x but the current release of NServiceBus.AzureStorageQueues is locked at 9.x via the nuget dependency range 
Can this be bumped so the dependencies align?

//cc @SeanFeldman  as discussed

**Comment by SeanFeldman** [comment]
@Particular/azure-maintainers are there any hard dependencies on Json.NET 9.x? Please update the list below.

- ASB: no
- ASQ: 
- ASP: 
- Azure.DataBus: 
- Azure.Host:

**Comment by danielmarbach** [comment]
Checked ASQ and it is a NO.

**Comment by yvesgoeleven** [comment]
@danielmarbach according to nuget it is https://www.nuget.org/packages/NServiceBus.Azure.Transports.WindowsAzureStorageQueues/
should the dependency be removed?

**Comment by danielmarbach** [comment]
@yvesgoeleven ah then I misunderstood the definition of hard dependency. I thought @SeanFeldman meant a hard dependency means that we have code that blocks upgrading to v10. I'll correct.

**Comment by SeanFeldman** [comment]
My apology. I should have be more specific. If there's a dependency _and_ it's a hard dependency on version 9. As far as I know, we don't require specific version of json.net anywhere.

**Comment by Scooletz** [comment]
ASQ will require JSON on its own to serialize messages with `DelayedDelivery` but is not version dependent. We had this discussion before about opening the dependencies' range. My understanding is that being given the requirement above, we should bump up the dependency to make it aligned to `10` and leave it as explicit one in the nuspec.

**Comment by yvesgoeleven** [comment]
Right, that discussion... I'm still all pro to test it once and opening the range in nuspec instead of telling people to ignore dependencies. I don't want to open this discussion again however.

**Comment by SeanFeldman** [comment]
Looked at Host.AzureCloudService and DataBus.AzureBlobStorage - don't see anything there.
