### ISSUE TITLE
Multi storage account support

### ISSUE THREAD

**Issue by yvesgoeleven** [Particular/NServiceBus.AzureStorageQueues#21]
Multi account support is needed to allow large customers to run on top of multiple storage accounts. Today, they can only send to other accounts, but this approach is a bit limited. We sould
- [ ] allow transports to use multiple accounts in active/active, active/passive modes, sharded
- [x] enable receive from a queue in all accounts

**Comment by yvesgoeleven** [comment]
Let's park this one till after v6, haven't heard back from the customer that needed this

**Comment by andreasohlund** [comment]
Would this be something we can add in a minor version? (or do we foresee the need to modify the transport seam)

**Comment by andreasohlund** [comment]
@Particular/azure-maintainers thoughts on https://github.com/Particular/NServiceBus.AzureStorageQueues/issues/21#issuecomment-200227746 ?

**Comment by SeanFeldman** [comment]
@yvesgoeleven did you have a chance to follow up with the customer that was asking for this feature?
It is a feature, so could be added in minor IMO.

**Comment by yvesgoeleven** [comment]
@SeanFeldman I did a while ago, but didn't get a reply back. I wouldn't mind releasing it afterwards, it doesn't sound so urgent as I thought it was. But on the other hand @melkio has been working on it already, and said he would have it finished by end of the week.

**Comment by SeanFeldman** [comment]
The decision was that for any feature added it needs to be compatible with the platform or be a platform-wide feature to begin with. Closing.
