### ISSUE TITLE
Messages that cannot be deleted go through the recovery

### ISSUE THREAD

**Issue by Scooletz** [Particular/NServiceBus.AzureStorageQueues#215]
When a message fails to get deleted in https://github.com/Particular/NServiceBus.AzureStorageQueues/blob/develop/src/Transport/AtLeastOnceReceiveStrategy.cs#L37 and throws an exception, it is handled via `errorPipe` and is tried to be deleted again ad the end of strategy https://github.com/Particular/NServiceBus.AzureStorageQueues/blob/develop/src/Transport/AtLeastOnceReceiveStrategy.cs#L73 which should not happen.

Messages that fail to get deleted should not go through `errorPipe` and just be logged (they do not exist anymore). The question WHY a message is picked up and deleted by something else is a separate thing to solve.

A sample output from the logger attached to ASP tests, where a message is tried to be deleted (fails for some reason), then it's sent to error queue and tried to be deleted / acknowledged again, which again, fails

```
DELETE /sendingfromasagatimeout-endpoint/messages/1234?popreceipt=ABCD 
HEAD /error?comp=metadata 
POST /error/messages 
DELETE /sendingfromasagatimeout-endpoint/messages/1234?popreceipt=ABCD
```

**Comment by Scooletz** [comment]
Ping @Particular/azure-maintainers

**Comment by SeanFeldman** [comment]
@Scooletz are you saying that the message once have gone through the pipeline and failed to be deleted should not be retried? Since this is `at-least-once` strategy, why shouldn't it be retried?

**Comment by danielmarbach** [comment]
@Scooletz What failure scenarios are possible here?

In competing consumer scenario a message can be picked up, processed again once visible and then be acked by someone else and in that case the ACK fails?

How can we exclude other scenarios? Isn't it safer to go through the error pipe again?

**Comment by Scooletz** [comment]
@SeanFeldman valid point. 

@danielmarbach I understand your question as "what happends when it fails the way you describe it?". `ReceiveStrategy.Receive` throws, which is logged with `WARN` in the `MessagePump`. So it won't propagate any further.

We made the scenario with competing consumer failing less likely, by calculating the timeout on client side as well and throwing a custom exception when/if needed.

I see your reasoning which resonates with the one provided by @SeanFeldman As it's `at-least-once` and failing does not crush the endpoint we can leave it as it is, correct @SeanFeldman @danielmarbach ?

**Comment by danielmarbach** [comment]
I would say so yes.

**Comment by SeanFeldman** [comment]
👍
