### ISSUE TITLE
Check to see if we can get rid of json.net dependency

### ISSUE THREAD

**Issue by yvesgoeleven** [Particular/NServiceBus.AzureStorageQueues#221]
Connects to https://github.com/Particular/NServiceBus.AzureStorageQueues/issues/235

To avoid version conflicts with other libraries that use json.net, it would be better if we didn't

**Comment by Scooletz** [comment]
The only place that we use it is #220 , native delayed delivery. If we get rid of it from there, it would be fine to remove it.

**Comment by Scooletz** [comment]
The dependency is nuspec is already gone. This PR #243 is removing the unneeded reference from the project.

**Comment by Scooletz** [comment]
#243 has been merged
