### ISSUE TITLE
Transport address translation should be consolidated and performed by ASQ TransportInfrastructure 

### ISSUE THREAD

**Issue by SeanFeldman** [Particular/NServiceBus.AzureStorageQueues#236]
Current implementation of ASQ Infrastructure code has [transport address translation](https://github.com/Particular/NServiceBus.AzureStorageQueues/blob/a8584226a2c764e929b33680168da600141f3890/src/Transport/AzureStorageQueueInfrastructure.cs#L154) (`ToTransportAddress()`) that is not compatible with ASQ native service [queue naming constraints](https://docs.microsoft.com/en-us/rest/api/storageservices/Naming-Queues-and-Metadata?redirectedfrom=MSDN).

To compensate for that, the transport is using [QueueAddressGenerator](https://github.com/Particular/NServiceBus.AzureStorageQueues/blob/a8584226a2c764e929b33680168da600141f3890/src/Transport/QueueAddressGenerator.cs#L9) to perform the necessary translations address translations in several places:
- [`AzureMessageQueueCreator`](https://github.com/Particular/NServiceBus.AzureStorageQueues/blob/a8584226a2c764e929b33680168da600141f3890/src/Transport/AzureMessageQueueCreator.cs#L30) 
- [`AzureMessageQueueReceiver`](https://github.com/Particular/NServiceBus.AzureStorageQueues/blob/a8584226a2c764e929b33680168da600141f3890/src/Transport/AzureMessageQueueReceiver.cs#L48)
- [`Dispatcher`](https://github.com/Particular/NServiceBus.AzureStorageQueues/blob/a8584226a2c764e929b33680168da600141f3890/src/Transport/Dispatcher.cs#L60)

All these components receive addresses that have gone through `AzureStorageQueueInfrastructure.ToTransportAddress()` already, invoked by Core.

**Comment by SeanFeldman** [comment]
This code was introduced in ASQ v7. Need to review and verify if messages in flight are affected or not.

**Comment by SeanFeldman** [comment]
@danielmarbach could you please update the issue with the findings?

**Comment by danielmarbach** [comment]
The shared queue and the instance specific queue are translated by the core

https://github.com/Particular/NServiceBus/blob/develop/src/NServiceBus.Core/Transports/Receiving.cs#L24
https://github.com/Particular/NServiceBus/blob/develop/src/NServiceBus.Core/Transports/Receiving.cs#L29

The error and audit queues are not. All queues for dispatching are not translated by the core therefore this responsibility is a responsibility of the transport. Furthermore it cannot be assumed that queues available in the QueueBindings are translated before passed to the installers. Therefore I think it is best to leave the address generator in the places it already was. Thoughts @Particular/azure-maintainers ?

**Comment by danielmarbach** [comment]
Raised https://github.com/Particular/NServiceBus/issues/4948

**Comment by yvesgoeleven** [comment]
aka the translation must be idempotent as we don't know how often it will be done?

**Comment by danielmarbach** [comment]
I would more say:

aka we cannot assume a queue is translated

**Comment by danielmarbach** [comment]
Core is patched and merged
ASQ build problems are solved
Backported to develop is done
Announcement done and released
