### ISSUE TITLE
JsonSerializer is removed from the core version vNext

### ISSUE THREAD

**Issue by danielmarbach** [Particular/NServiceBus.AzureStorageQueues#239]
We are currently setting the JsonSerializer as the default serializer in https://github.com/Particular/NServiceBus.AzureStorageQueues/blob/cfbeabb9c5f2fa2676632a69ea454d001f7a7727/src/Transport/AzureStorageQueueTransport.cs#L29

In Versions 7 and above of NServiceBus the JsonSerializer has been removed. Use the external [Json.NET Serializer](/nservicebus/serialization/newtonsoft.md) instead. See also [Compatibility between the core and external Json.NET serializer](/nservicebus/serialization/newtonsoft.md#compatibility-with-the-core-json-serializer).

**Comment by SeanFeldman** [comment]
Serialization is a mandatory setting and needs to be provided.
