### ISSUE TITLE
Code only configuration API

### ISSUE THREAD

**Issue by yvesgoeleven** [Particular/NServiceBus.AzureStorageQueues#24]
Connects to #22

To be consistent with core v6 & the rest of the transports & persistences, we should switch to a code only configuration model on top of SettingsHolder.

Todo: should we provide an overlay for backward compat of xml based config model as well?

**Comment by yvesgoeleven** [comment]
This item replaces https://github.com/Particular/NServiceBus.AzureStorageQueues/issues/15

**Comment by Scooletz** [comment]
Should the old config section be removed or marked with `ObsoleteEx` for now? I cannot find any rule for that beside https://github.com/Particular/Vision/issues/22

**Comment by SzymonPobiega** [comment]
Well, we need to somehow tell the users that the values there are no longer used in any way...

**Comment by yvesgoeleven** [comment]
I noticed core is also going to remove all config sections, what's the plan there to tell users about it?

**Comment by SeanFeldman** [comment]
@SzymonPobiega I wonder about the same https://github.com/Particular/NServiceBus.AzureStorageQueues/issues/24#issuecomment-180526821

**Comment by dvdstelt** [comment]
The original item #15 said ConfigSection should take precedence over configuration done in code. That's not what I'm used to, from other Microsoft libraries. For example in WCF everything in config is overridden by code configuration.

**Comment by Scooletz** [comment]
I agree with @dvdstelt. I'm used to **Code over configuration** rule as well.

**Comment by dvdstelt** [comment]
And that's also what this says : https://github.com/Particular/Vision/issues/22#issuecomment-105154194

**Comment by tmasternak** [comment]
@dvdstelt given that `Code over config` PR has been merged is there anything else left to do here? If yes let's move that to different issue and close this one. It's not a must-have for V6 release, right?
