### ISSUE TITLE
Pub/sub between storage accounts is broken

### ISSUE THREAD

**Issue by SeanFeldman** [Particular/NServiceBus.AzureStorageQueues#246]
Affected version: 7 (NServiceBus 6).

GG issue: https://groups.google.com/forum/m/#!topic/particularsoftware/PulFwHKKx58
Support case: https://eu1.salesforce.com/apex/Case?num=00030037

**Comment by yvesgoeleven** [comment]
MessageEndpointMappings still exist, so can serve as workaround until we can add a new api for this

**Comment by SeanFeldman** [comment]
`MessageEndpointMappings` cannot be combined with some features in v7 of the transport (such as secured connection strings. Also, `MessageEndpointMappings` is gone from NSB v7.

**Comment by SeanFeldman** [comment]
Another customer is affected by this.

**Comment by yvesgoeleven** [comment]
Doco https://github.com/Particular/docs.particular.net/pull/3339
