### ISSUE TITLE
Send-only endpoint with native delayed delivery should not poll for delayed messages

### ISSUE THREAD

**Issue by SeanFeldman** [Particular/NServiceBus.AzureStorageQueues#248]
## Who's affected

Anyone running send-only endpoints using Azure Storage Queues version 7.4 with Delayed Delivery

## Symptoms

Send-only endpoint should only be able to send messages and defer those, but not receive. That would include delayed/deferred messages either. Despite that, `DelayedMessagesPoller` is still enabled and is polling for delayed messages.

---

Original issue: [GG post](https://groups.google.com/d/msg/particularsoftware/he5-szClQmY/jPoUZGiuAQAJ)

**Comment by SeanFeldman** [comment]
This is actually the correct behavior.

A send-only endpoint can defer messages.

```c#
var config = new EndpointConfiguration("sending-endpoint");
config.SendOnly();
var endpoint = await Endpoint.Start(config);

var so = new SendOptions();
so.DelayDeliveryWith(TimeSpan.FromSeconds(20));
so.SetDestination("destination");
await endpoint.Send(new Message {Text = "delayed by 20 seconds"}, so);
```

When the transport [delayed deliver](https://docs.particular.net/transports/azure-storage-queues/delayed-delivery) is enabled (version 7.4 of the ASQ transport and above), the sending endpoint is storing any delayed messages in a storage table until those can be dispatched. To determine when and what messages can be dispatched, the endpoint has to poll for the delayed messages table. That's what you see.

**Comment by GeertDepickere** [comment]
Thanks for explaining this behavior.
However: 
- As you know, polling Azure storage results in extra costs...
- So is there an option to disable this polling when I know that I am not using delayed message sending from my send-only endpoint?

**Comment by SeanFeldman** [comment]
I see your point @GeertDepickere. Polling is [backing off](https://github.com/Particular/NServiceBus.AzureStorageQueues/blob/7bbf96931d40bf4d67b42d7d9e3e34fdeeb3456d/src/Transport/DelayDelivery/DelayedMessagesPoller.cs#L197) once there are no delayed messages found, but it will go to down to as frequent every [30 seconds](https://github.com/Particular/NServiceBus.AzureStorageQueues/blob/7bbf96931d40bf4d67b42d7d9e3e34fdeeb3456d/src/Transport/BackoffStrategy.cs#L18) by default or whatever the configured maximum `MaximumWaitTimeWhenIdle` (no more than [60 seconds](https://github.com/Particular/NServiceBus.AzureStorageQueues/blob/7bbf96931d40bf4d67b42d7d9e3e34fdeeb3456d/src/Transport/Config/AzureStorageTransportExtensions.cs#L27)). So yes, still polling.

I've raised a [feature request](https://github.com/Particular/NServiceBus.AzureStorageQueues/issues/250) to be able to turn delayed delivery polling entirely off. Please comment on that issue in case you'd like to add information. Thank you.
