### ISSUE TITLE
FIPS compliance: Make MD5 algorithm replaceable with SHA1

### ISSUE THREAD

**Issue by yvesgoeleven** [Particular/NServiceBus.AzureStorageQueues#25]
Because MD5 algorithm, used for renaming queues when entity name is to large, is not FIPS compliant, we should make it replaceable with SHA1. Similar to https://github.com/Particular/NServiceBus.AzureServiceBus/pull/79

**Comment by Scooletz** [comment]
@yvesgoeleven What about backward compatibility? How would you approach that? Use both and check if the old exists? Or pull from both?

**Comment by yvesgoeleven** [comment]
This should be configurable, MD5 should probably stay the default? /cc @SeanFeldman

**Comment by Scooletz** [comment]
Oh, if we can keep both algorithms and provide a choice, in my opinion we should use SHA1 and provide a configuration method `UseLegacyMD5QueueNameShortener` or similar.

**Comment by SeanFeldman** [comment]
Can I suggest to avoid the word 'legacy'? Anything that is done at point in time `t` can become a legacy sooner or later.

As for the default - if an existing customer has queues in production shortened using MD5 and we'll use SHA1 based strategy by default in the new endpoints, MD5-based queues won't be found. It's fine as long as we we can intelligently let customers know what to do and how to fix it.

**Comment by Scooletz** [comment]
Yes, I can remove that. I wanted explicitly connect with that `t` in the past, where we were using MD5. I can name it without legacy ofc, but this doesn't show why one should use MD5 or default SHA1 hashing (in the newest version).

**Comment by yvesgoeleven** [comment]
honestly, nobody outside US government related projects will care about this, MD5 doesn't work when a certain FIPS related registry setting is set... not the case for 99% of our customers

**Comment by Scooletz** [comment]
Will make `SHA1` opt in then, leaving `MD5` default.
