### ISSUE TITLE
Remove shortening from the transport

### ISSUE THREAD

**Issue by SeanFeldman** [Particular/NServiceBus.AzureStorageQueues#251]
~~With .NET Standard, cryptography algorithms SHA1 and MD5 are deprecated and are not available.~~
We should take the same approach as with ASB in version 7.0 where sanitization is delegated to the customers.

This is a breaking change.

### PoA
- [x] Remove shortening and update API
- [x] Doco ([PR](https://github.com/Particular/docs.particular.net/pull/3189))
  * Custom sanitization sample
  * Upgrade guide

**Comment by SeanFeldman** [comment]
This is an API change and needs to be done prior to beta. FYI @Particular/dotnetcore-launch-squad

**Comment by DavidBoike** [comment]
@SeanFeldman What about `SHA1.Create()` and `MD5.Create()`? Using that in Raven.

**Comment by SeanFeldman** [comment]
Those are fine as they are invoking whatever is available on the platform code is running on @DavidBoike .

**Comment by SeanFeldman** [comment]
The reason for this change in the general description was misleading. Updated.

**Comment by SeanFeldman** [comment]
**Update**
PR is merged, doco + sample + upgrade guide is required.

**Comment by SeanFeldman** [comment]
Beta on myget, closing.
