### ISSUE TITLE
Rewrite tests that leverage 'BuildAnotherConnectionString'

### ISSUE THREAD

**Issue by yvesgoeleven** [Particular/NServiceBus.AzureStorageQueues#276]
[This method](https://github.com/Particular/NServiceBus.AzureStorageQueues/blob/27026434ad535e6dd0a3b6d9450fb1184a493f36/src/AcceptanceTests/Utils.cs#L38) does return another connectionstring (format), but it still points to the same account. Some of the tests leveraging it assume it's also another account. So these tests aren't actually testing anything

- ~~Create a resource set of new accounts~~
- ~~Create another environment variable for the second account~~
- ~~Assign environment variable with one of the new accounts~~
- [x] Rewrite method to use that new env variable
- [x] Update tests accordingly

**Comment by SeanFeldman** [comment]
The project already has 2 environment variables for connection strings, leveraging the same connection strings pool (TC shared variable). Going to use that.

**Comment by SeanFeldman** [comment]
Tests were updated to use 2 connection strings.
Everything works as expected.
