### ISSUE TITLE
Native pub/sub

### ISSUE THREAD

**Issue by SeanFeldman** [Particular/NServiceBus.AzureStorageQueues#277]
## Overview

The transport has recently introduced native delayed delivery which solve the problem of duplicate dispatching and allows transport to be self-contained, removing reliance on Persistence and additional package.

Similar approach could be applied for Pub/Sub. Since the dawn of the days, the native ASQ service did not support native pub/sub and was assumed to be a message-driven pub/sub transport, which requires an additional Persistence package. Persistence of choice for ASQ would most likely be Azure Storage persistence (ASP), which is based on the same Storage service as ASQ.

A preliminary spike (PR #198) was made to demonstrate native pub/sub.

## Questions to be addressed

The following questions should be addressed **before** we get this going:

1. Azure Storage Persistence and native pub/sub - is it possible to mix the two or do we need a migration that requires a production stop? With Native delayed delivery the transport could operate in a hybrid mode, still receiving from TimeoutManger and dispatching using native delayed delivery infrastructure. With pub/sub, the core either accepts message driven or centralized. Needs to be analyzed more.
    - If publisher is upgraded, but subscribers are not, to work properly, there are two conditions
        1. Subscribe/Unsubscribe messages need to be respected by an upgraded publisher. Can be achieved via behavior that would handle those messages to handle subscriptions information update internally against storage account.
        1. Subscriptions table needs to be shared to ensure endpoint that are not upgraded and publish have accurate information.
1. Subscriptions table(s) - how to?
    1. ~~A table per endpoint.~~
        - ❌  Coupling between publisher and subscriber
        - ❌ or Publisher needs to scan all subscribers to find who's subscribing to an event
    1. ~~A table per event (to decouple pub/sub).~~
        - ❌ polymorphic events would be painful to detect and implement with this approach
    1. A single table where PartitionKey (PK) is event type and RowKey (RK) is subscriber.
        - ✔️  Decoupled publisher and subscriber
1. Caching subscriptions. To ensure we don't accumulate unnecessary storage costs.
1. Event handling for creation / deletion by multiple instances of an endpoint. Similar to ASB, this could happen and we should not fail.
1. Polymorphic message subscription and publishing (BaseEvent vs DerivedEvent).
    - The transport would need to do what core is currently performing when subscription is created - determine event's hierarchy and publish a message copy for each subscriber found in the subscriptions table associated with message hierarchy.
1. What releasing this feature would look like?
    1. Conversion of existing subscriptions - not needed if a single shared table approach is used.
    1. How to release? (Major / ~~minor~~) - due to possibility to run each point with on a different storage account for persistence, a single table would be a breaking change.
    1. Upgrade process?
1. Additional questions:
    1. Should subscriptions be allowed to stored on a different storage account? ASP could be configured to use a different storage account than ASQ. - NO.
    1. Subscription versioning?

**Comment by SeanFeldman** [comment]
After analyzing this issue, this needs to be a major release.
Given current major release (ASQ 8.0 with Core 7.0) is getting to the RC stage, I recommend we postpone this feature until the **next** major.
/cc @Particular/azure-maintainers @andreasohlund

**Comment by andreasohlund** [comment]
>After analyzing this issue, this needs to be a major release.

Can you elaborate on the reasons for needing a major?

**Comment by SeanFeldman** [comment]
To decouple publishers and subscribers and allow side-by-side upgrade, a single table on a single account would be required. Today ASP allows each endpoint to use both table per endpoint and different storage accounts. Therefore it would be a breaking change if we'd require a single account / table be used.

**Comment by andreasohlund** [comment]
>Therefore it would be a breaking change if we'd require a single account / table be used.

But we should be able to make native pubsub opt-in so new users can start benefit from this in a minor and have the full migration story ready for vNextMajor?

Ie:  `.UseTransport<ASQ>().UseNativePubSub();`

**Comment by SeanFeldman** [comment]
@andreasohlund and if they run ASQ on different storage accounts and opt in for native pub/sub, what's that going to look like? I've updated bullet point 1 with more details, have a look.

**Comment by andreasohlund** [comment]
>and if they run ASQ on different storage accounts and opt in for native pub/sub, what's that going to look like? I've updated bullet point 1 with more details, have a look.

I'm only talking about new users, so they would by definition not have any existing storage accounts since they are starting fresh.

Users with with separate storage accounts would have to wait until vNextMajor or do some manual migration

**Comment by danielmarbach** [comment]
I think no matter whether it needs a major or not in my opinion right now is not the right time to build it. Releasing the core v7 compatible version as well as addressing the ASB client rewrite has more prio for me. I vote for backlog. @andreasohlund we can make a decision in Platform Development to move consistently towards native pub/sub in all the transports and then we can address this. Otherwise, we'd be doing it under maintainer budget which feels off.

**Comment by andreasohlund** [comment]
>I think no matter whether it needs a major or not in my opinion right now is not the right time to build it. Releasing the core v7 compatible version as well as addressing the ASB client rewrite has more prio for me. I vote for backlog

Agreed, was just saying that we don't have to wait for the next major. I'm happy to backlog

>we can make a decision in Platform Development to move consistently towards native pub/sub in all the transports and then we can address this

I will raise and issue

**Comment by andreasohlund** [comment]
Not yet, I'll keep this issue assigned to me until it's done

**Comment by SeanFeldman** [comment]
Closing this issue for now. We can review and reopen if needed later.
