### ISSUE TITLE
ToTransportAddress should use dash instead of dot for satellites

### ISSUE THREAD

**Issue by danielmarbach** [Particular/NServiceBus.AzureStorageQueues#279]
also remove the test sanitizer

**Comment by yvesgoeleven** [comment]
Note: verify the old guid generation logic, to see if this could not lead to different guids if set by the user

**Comment by SeanFeldman** [comment]
Closed via https://github.com/Particular/NServiceBus.AzureStorageQueues/commit/896a81233a3c08f45ca02e6a7129fa36671ea45b

**Comment by SeanFeldman** [comment]
@yvesgoeleven the note that you had - how applicable it is? In v7 of the transport it would never work.
Please re-open the issue _and_ add context if you think we're missing something
