### ISSUE TITLE
Ensure backward compatible guid generation

### ISSUE THREAD

**Issue by yvesgoeleven** [Particular/NServiceBus.AzureStorageQueues#282]
1. Ensure that https://docs.particular.net/transports/azure-storage-queues/sanitization#backwards-compatibility actually contains the backward compat guid generation code, similar to asb https://docs.particular.net/transports/azure-service-bus/sanitization?version=asb_8#automated-sanitization-backward-compatibility-with-versions-6-and-below, instead of just pointing to the sample.

2. Run a test with the backward compat sanitization logic before and after applying this change, https://github.com/Particular/NServiceBus.AzureStorageQueues/pull/280, and see if the generated guids are still the same?

**Comment by yvesgoeleven** [comment]
After a first look at the backward compat code, I think it's not going to be an issue, guid generation is based on the string with dots replaced https://github.com/Particular/docs.particular.net/blob/master/samples/azure/storage-queues/ASQ_8/Shared/BackwardsCompatibleQueueNameSanitizer.cs

**Comment by yvesgoeleven** [comment]
Looks like we broke guid generation between 6 and 7, and again between, 7 and 8

**Comment by SeanFeldman** [comment]
Quick evaluation shows the following.

### Queues w/o disriminator

original queue name: `Samples.Azure.StorageQueues.Endpoint1.with.a.very.logn.endpoint.name`

| **Version** | Code Location| Processed name |
|----|------|-----|
| v6 | Transport | samples-azure-storagequeue-c8ae534d-c83b-2186-cc6b-5380a092733a |
| v7 | Transport | samples-azure-storagequeue-c8ae534d-c83b-2186-cc6b-5380a092733a |
| v8 | Sample / doco| samples-azure-storagequeue-3587b420-7b25-c81c-a605-21a56db8a506 |

**Comment by SeanFeldman** [comment]
Based on what I've seen, the sample/doco code to sanitize and short queue names needs to be updated not to use the original queue name. Will raise a PR.

**Comment by SeanFeldman** [comment]
### Version 6

1. [`AzureMessageQueueUtils.GetQueueName(address);`](https://github.com/Particular/NServiceBus.AzureStorageQueues/blob/97e2bb9b443fc25c8273b5d7b2fa33a84b45056a/src/Transport/AzureMessageQueueUtils.cs#L13) is used whenever an `Address` needs to be converted into a queue name.
2. `address.Queue` portion of the `address` is lower cased and sanitized. This value is used for further calculations
3. queue name is sanitized
    1. Sanitization: all illegal characters are replaced with dashes and multiple sequential dashes are replaced with a single dash.
4. All dots (`.`) are replaced with dashes (`-`). // redundant as it would be covered by sanitization step
5. If sanitized queue name exceeds 63 characters, it's truncated by the length of an appended `-GUID` value.
    1. GUID: is an MD1 hash of the the queue name from step 2
    2. _If_ truncated queue name ends with a dash, it's removed to avoid sequential dashes.

### Version 7

1. Similar to v6, [`QueueAddressGenerator.GetQueueName(address)`](https://github.com/Particular/NServiceBus.AzureStorageQueues/blob/master/src/Transport/QueueAddressGenerator.cs#L23) is used whenever an address needs to be converted into a queue name. Two differences with v6 are:
    1. address passed in is a plain `string`.
    1. A shortening algorithm can be either MD5 (default) or SHA1. 
2. `address` is lower cased and retrieved from cache. If cache doesn't have value for the address, queue name is calculated.
    1. Sanitization: all illegal characters are replaced with dashes and multiple sequential dashes are replaced with a single dash.
    1. If sanitized queue name exceeds 63 characters, 
        1. All dots (`.`) are replaced with dashes (`-`). // redundant as it would be covered by sanitization step
        1 It's truncated by the length of an appended `-GUID` value.
        1. GUID: is a hash of the the queue name from step 2 using one of the hashing algorithms. 
        1. _If_ truncated queue name ends with a dash, it's removed to avoid sequential dashes.

### Version 8

* Unlike previous versions, [`QueueAddressGenerator.GetQueueName(address)`](https://github.com/Particular/NServiceBus.AzureStorageQueues/blob/e90d3c7e964d4849ac30d0173d5a5a7fa4a0b0ab/src/Transport/QueueAddressGenerator.cs#L13) is invoking user-provided sanitizer.
* [Default sanitizer](https://github.com/Particular/NServiceBus.AzureStorageQueues/blob/e90d3c7e964d4849ac30d0173d5a5a7fa4a0b0ab/src/Transport/Config/DefaultConfigurationValues.cs#L16) returns `address` value as its queue name

**Comment by SeanFeldman** [comment]
Closing this issue in favor of https://github.com/Particular/docs.particular.net/issues/3255
