### ISSUE TITLE
ASQ Performance degradation

### ISSUE THREAD

**Issue by yvesgoeleven** [Particular/NServiceBus.AzureStorageQueues#285]
From the results of the performance test runs, it seems that ASQ performance has significantly decreased between 6 and 7.

https://github.com/Particular/DotNetCoreLaunch/issues/54#issuecomment-336710318

**Comment by yvesgoeleven** [comment]
@ramonsmits What where the concrete numbers (not in %)?

**Comment by SeanFeldman** [comment]
I'll _assume_ all the tests were performed with the **West Europe** data centre.

**Comment by ramonsmits** [comment]
Yes, all for Azure in West Europe DC.

@yvesgoeleven results are available here: https://drive.google.com/open?id=1fhqRsbRsrsC4H9kVI6zKz3BGAb9xZEq4C4Ib_Rh79Og , just open in Sheets and add a filter on the transport column.

**Comment by ramonsmits** [comment]
There was an issue found in the perftests https://github.com/Particular/EndToEnd/pull/266/files which  could have impact in these results. I'll rerun the tests and update this issue with the results next week.

**Comment by yvesgoeleven** [comment]
@ramonsmits is this sitll an issue?

**Comment by ramonsmits** [comment]
@yvesgoeleven Based on the results of last week is that V7 is still slower then V6:

- https://drive.google.com/open?id=1IROuzXzNfSDHF7Fffz6udzkgliw8QOGvmdTNAg-U3r0

**Comment by SeanFeldman** [comment]
Was it executed against `West EU` only or against other data centers as well @ramonsmits ?

**Comment by ramonsmits** [comment]
@SeanFeldman West EU for all versions as that is the lowest latency for me but what difference would that make?

**Comment by SeanFeldman** [comment]
It's not just about latency, but also about maximum thoughput. West EU is one of the most condenced datacetres. I would suggest to try one of the US based servers to see if there are differences. Assuming code is executed near by (VM).

**Comment by ramonsmits** [comment]
@SeanFeldman I'm testing it from my home uplink which has so far always been faster than testing it from a VM but I've never tested using a very expensive one.

Still, why would that give other results? Same tests configuration with ASQ for core v6 is slower then for v7, not sure what bandwidth has got to do with that?

**Comment by SeanFeldman** [comment]
There are multiple factors that could influence the results. If you see the same behaviour with another datacentre, I'd explore the possibility of the differences between versions of the Storage Client used by ASQ.

**Comment by ramonsmits** [comment]
@seanfarmar What input do you require from me so that @Particular/azure-maintainers can investigate this? If the following guidance is not enough to get the tests running in your environment then please let me know so I can help you run them.

- https://github.com/Particular/EndToEnd/blob/master/src/PerformanceTests/readme.md

**Comment by yvesgoeleven** [comment]
@ramonsmits we have no idea where to start, all we did this release is upgrade core and azure sdk, we made hardly any changes ourselves that can impact the performance

https://github.com/Particular/NServiceBus.AzureStorageQueues/issues?q=is%3Aissue+milestone%3A8.0.0+is%3Aclosed

**Comment by ramonsmits** [comment]
I'm not sure about the SDK but @danielmarbach found the reason for the performance issue with SQS and ASQ on dotnet core and created a PR for ASQ after doing some research.

- https://github.com/Azure/azure-storage-net/pull/579

If you do not think this requires additional investigation because the performance decrease isn't significant then I guess you can close this.

**Comment by yvesgoeleven** [comment]
@Particular/azure-maintainers thoughts?

**Comment by SeanFeldman** [comment]
That PR also [involves Storage Tables](https://github.com/Azure/azure-storage-net/pull/579/commits/aec036bb0bdb1f53e7e14aa5bdbcb47722f80d2a).

Ideally we'd need to compare apples to apples. If this PR could go through, we could re-run the tests.
I have no idea what else could it be.

**Comment by danielmarbach** [comment]
We don't think the difference is large enough to justify investigation efforts in this area. Closing the issue. Thanks @ramonsmits for raising it.
