### ISSUE TITLE
Remove the dependency on the core serializer

### ISSUE THREAD

**Issue by Scooletz** [Particular/NServiceBus.AzureStorageQueues#29]
Azure Storage Queue transport uses core component `IMessageSerializer` to serialize its own `MessageWrapper` being used to pass all the message data by ASQ. This dependency must be changed, and ASQ should use its own serializer, even if it's aligned to the one selected in core.
This involves:
- [x] inspect `ReadOnlySettings` for a type of a selected serializer. For JSON and Xml provide internal methods for serialization/deserialization. Use build in .NET serializers
- [x] for other types, throw a descriptive exception leading to transport extension methods for registering these two methods (like `AzureStorageTransportExtensions.SerializeWith(this TransportExtensions<AzureStorageQueueTransport> config, Func<MessageWrapper,byte[]> serialize, Func<byte[],MessageWrapper> deserialize)`
- [x] provide wire compatibility tests for xml & json

/cc @danielmarbach @andreasohlund

**Comment by Scooletz** [comment]
This will be covered by tests provided by: https://github.com/Particular/ProductionTests/issues/45

**Comment by Scooletz** [comment]
There's a discussion touching this topic: https://github.com/Particular/NServiceBus/issues/3419 If the core makes one method public, it'll make this PR useless as we'll be able to use core serializer. Making this PR [WIP] then

**Comment by andreasohlund** [comment]
@yvesgoeleven is arranging a call on monday/early next week to talk this through and get agreement on this

**Comment by Scooletz** [comment]
There's a discussion touching this topic: https://github.com/Particular/NServiceBus/issues/3419 If the core makes one method public, it'll make this PR useless as we'll be able to use core serializer. Making this PR [WIP] then

**Comment by Scooletz** [comment]
PR merged to develop
