### ISSUE TITLE
Delayed Delivery Feature Does Not Disable and Spams Blob/Tables in Storage Account

### ISSUE THREAD

**Issue by afyles** [Particular/NServiceBus.AzureStorageQueues#292]
## Who's affected

Anyone using Azure Storage Queues transport with native delayed deliver and wants to turn delayed delivery off.

## Symptoms

There's no way to disable delayed delivery to save the costs of Storage operations. As a result of that, the poller keeps connecting to Storage service (tables and blobs).

## Original issue

We are using .NET Web API to send messages to a backend endpoint.  No matter what we do we cannot get the Delayed Delivery feature to disable and stop making thousands of calls to the storage account in an attempt to acquire leases.  We see the traffic via Fiddler and as dependency calls in AppInsights.  Our Web API startup looks like the following:

```
EndpointConfiguration endpointConfiguration = new EndpointConfiguration("ProductWebApiEndpoint");
            endpointConfiguration.DisableFeature<MessageDrivenSubscriptions>();
            endpointConfiguration.SendOnly();
            TransportExtensions<AzureStorageQueueTransport> transport = endpointConfiguration.UseTransport<AzureStorageQueueTransport>();
            transport.DelayedDelivery().DisableTimeoutManager();
            transport.ConnectionStringName("ProductStorage");
            IEndpointInstance endpointInstance = Endpoint.Start(endpointConfiguration).GetAwaiter().GetResult();
            ContainerBuilder builder = new ContainerBuilder();
            builder.RegisterInstance<IMessageSession>(endpointInstance);
            config.DependencyResolver = new AutofacWebApiDependencyResolver(builder.Build());
```

We've tried the latest stable and the latest beta packages.  Here is the stable versions:
Autofac 4.6.2
Autofac.WebApi2 4.1.0
NServiceBus 6.4.3
NServiceBus.Azure.Transports.WindowsAzureStorageQueues 7.4.2
WindowsAzure.Storage 8.4.0

We would like to just shut the feature off, but we can't figure out how.  Sample Fiddler response:

HTTP/1.1 409 There is already a lease present.
Content-Length: 221
Content-Type: application/xml
Server: Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0
x-ms-request-id: 5e7ee2bd-001e-0020-6073-68cde1000000
x-ms-version: 2017-04-17
Date: Tue, 28 Nov 2017 18:06:43 GMT

<?xml version="1.0" encoding="utf-8"?><Error><Code>LeaseAlreadyPresent</Code><Message>There is already a lease present.
RequestId:5e7ee2bd-001e-0020-6073-68cde1000000
Time:2017-11-28T18:06:43.4927873Z</Message></Error>

**Comment by yvesgoeleven** [comment]
@afyles  On the object returned by `transport.DelayedDelivery()` you can call `DisableDelayedDelivery()` to turn it off.

**Comment by SeanFeldman** [comment]
```c#
var delayedDelivery = transport.DelayedDelivery();
delayedDelivery.DisableDelayedDelivery();
```
Documentation [link](https://docs.particular.net/transports/azure-storage-queues/delayed-delivery?version=asq_8#how-it-works-disabling-delayed-delivery).

**Comment by SeanFeldman** [comment]
Unfortunately, that doesn't help. The issue @afyles has is with ASQ v7.

Disabling delayed delivery is [available in v8](https://github.com/Particular/NServiceBus.AzureStorageQueues/blob/b995f90db6190b3eb8beeb14eee4f80a472d2841/src/Transport/Config/DelayedDeliverySettings.cs#L44), but [**not in v7**](https://github.com/Particular/NServiceBus.AzureStorageQueues/blob/455df9fa3a0dac5739514ebee974867c19fcd222/src/Transport/Config/DelayedDeliverySettings.cs#L7).

**Comment by afyles** [comment]
I think we tried v8 and disabling.  Let us try again.

**Comment by SeanFeldman** [comment]
Let me sum it up:
1. Disabling delayed retries is possible with v8, but not with v7
1. Even with disabled delayed retries in v8, the poller is still accuring Storage costs as it's [not disabled](https://github.com/Particular/NServiceBus.AzureStorageQueues/blob/b995f90db6190b3eb8beeb14eee4f80a472d2841/src/Transport/AzureStorageQueueInfrastructure.cs#L195-L197). With v7 that's [also the case](https://github.com/Particular/NServiceBus.AzureStorageQueues/blob/455df9fa3a0dac5739514ebee974867c19fcd222/src/Transport/AzureStorageQueueInfrastructure.cs#L188-L190) _and_ delayed delivery can't be disable.

**Comment by yvesgoeleven** [comment]
@SeanFeldman looks like this is a bug

**Comment by SeanFeldman** [comment]
Bug for v8 (poller active when shouldn't) + a bug and missing feature on v7 (disabling delayed delivery).

**Comment by afyles** [comment]
Confirmed, still does not disable with v8.  Thanks for the quick response.

**Comment by SeanFeldman** [comment]
We should be patching v7 and port the fix for poller to v8.

**Comment by SeanFeldman** [comment]
@afyles with disabled delayed delivery, your endpoint will not be able to use
- Delayed retries
- Saga timeouts
- Deferred messages

Could you please confirm that by disabling delayed delivery you OK with those not being available?

**Comment by afyles** [comment]
Yes that is fine

**Comment by SeanFeldman** [comment]
Closed via https://github.com/Particular/NServiceBus.AzureStorageQueues/commit/ed7fa3bb605f1d859cbe20b19b5fc659ffa2b14c

**Comment by SeanFeldman** [comment]
@afyles thank you for raising the issue.
[7.5.0 was released](https://discuss.particular.net/t/nservicebus-azure-transports-windowsazurestoragequeues-7-5-0-minor-release-available/222) and contains API to disable native delayed delivery.
