### ISSUE TITLE
Cloud show-case has no NServiceBus version 7

### ISSUE THREAD

**Issue by SeanFeldman** [Particular/NServiceBus.AzureStorageQueues#303]
Only NServiceBus version 6 is posted

**Comment by danielmarbach** [comment]
@Particular/dotnetcore-launch-squad how do we make sure all relevant samples are up to date? Simon once raised https://github.com/Particular/docs.particular.net/issues/3104 for the snippets. Shouldn't we track something like that for samples and snippets in the launch wave repo and make sure it gets done for RTM?

**Comment by andreasohlund** [comment]
@danielmarbach good catch, I will make sure that this is tracked

**Comment by yvesgoeleven** [comment]
PR https://github.com/Particular/docs.particular.net/pull/3514

**Comment by SeanFeldman** [comment]
PR merged.
