### ISSUE TITLE
UseAccountAliasesInsteadOfConnectionStrings with default connection string exposes raw connections strings

### ISSUE THREAD

**Issue by SeanFeldman** [Particular/NServiceBus.AzureStorageQueues#309]
## Who's affected

- Anyone using Azure Storage Queues transport version 7.5.x and above

## Symptoms

When using ASQ with default connection string and alias to secure it, messages sent with raw connection string instead of alias.

### Details

Azure Storage Queues transport (ASQ) has a feature to [secure connections strings](https://docs.particular.net/transports/azure-storage-queues/multi-storageaccount-support#cross-namespace-routing-using-aliases-instead-of-connection-strings).

> In order to prevent accidentally leaking connection string values, it is recommended to use aliases instead of raw connection strings. When applied, raw connection string values are replaced with registered aliases removing the possibility of leaking a connection string value. **When using a single account, aliasing connection string is limited to just enabling it.** When multiple accounts are used, an alias has to be registered for each storage account.

This appear to be broken when a single (default) connection string is used. A separate [bug issue is raised ](https://github.com/Particular/NServiceBus.AzureStorageQueues/issues/308).
Unfortunately, the API is broken in a way that leads customers to assume that the default connection string is secured by invoking the API, when in reality it is not.

When API is called

```c#
transport.UseAccountAliasesInsteadOfConnectionStrings();
transport.DefaultAccountAlias("account_A");
```

Sending messages will contain the raw connection string rather than its alias as per documentation.

```json
{
  "IdForCorrelation": null,
  "Id": "7427f558-9e38-4959-9561-a869017ea425",
  "MessageIntent": 1,
  "ReplyToAddress": "samples-azure-storagequeues-endpoint1@UseDevelopmentStorage=true",
  "Headers": {
    "NServiceBus.MessageId": "7427f558-9e38-4959-9561-a869017ea425",
    "NServiceBus.MessageIntent": "Send",
    "NServiceBus.ReplyToAddress": "samples-azure-storagequeues-endpoint1@UseDevelopmentStorage=true",
  },
  "Body": "...",
  "CorrelationId": "7427f558-9e38-4959-9561-a869017ea425",
  "Recoverable": true
}
```

### Affected versions

- ASQ 7.4.x
- ASQ 7.5.x
- ASQ 8

### Expected behaviour

ASQ should [behave as ASB](https://docs.particular.net/transports/azure-service-bus/securing-connection-strings#backward-compatibility) and provide a default alias, which is used for the default connection string when connection strings should be secured.

**Comment by SeanFeldman** [comment]
Added a test in PR #310 to shows the issue.

**Comment by Scooletz** [comment]
The test provided by you @SeanFeldman made me think should we apply the same rule for all the cross-account tests and assert raw values of headers, without using NSB.

**Comment by SeanFeldman** [comment]
I'd suggest to treat that as a separate issue. Could you please raise it @Scooletz?

**Comment by Scooletz** [comment]
I've created [this issue](https://github.com/Particular/NServiceBus.AzureStorageQueues/issues/314).

**Comment by SeanFeldman** [comment]
Closed via https://github.com/Particular/NServiceBus.AzureStorageQueues/commit/cbe471c1d1190ca71c09c0f9f5dc8fdd51af5a28
