### ISSUE TITLE
Consider using raw messages for asserting multi storage account aliases

### ISSUE THREAD

**Issue by Scooletz** [Particular/NServiceBus.AzureStorageQueues#314]
Currently, tests that cover account aliases use ASQ transport on both ends, see [When_sending_messages_with_mapped_account_names](https://github.com/Particular/NServiceBus.AzureStorageQueues/blob/develop/src/AcceptanceTests/Configuration/When_sending_messages_with_mapped_account_names.cs). It could be beneficial to use a raw `CloudQueueClient` on one end (either sending or receiving) to ensure that the structure of the message is preserved properly and that the raw connection strings are truly replaced when this feature is enabled. 

This would additionally ensure wire compatibility.

**Comment by SeanFeldman** [comment]
The test above could be replaced with a single test for multiple storage accounts validation using the same approach taken in hotfix 7.5.3

**Comment by SeanFeldman** [comment]
`Is_enabled_and_sending_to_another_account_Should_audit_fully_qualified_queue` is already performing validation using native message and doesn't have to be updated. I had to merge `release-8.0` to `develop` to start the work, but that's not an issue. Closing issue as `Withdrawn`.
