### ISSUE TITLE
Are events supported in the ASQ transport?

### ISSUE THREAD

**Issue by MarcusChamberlain** [Particular/NServiceBus.AzureStorageQueues#323]
Hi

Are publishing events supported in Azure Storage Queues? I'm using the sample project found here: https://docs.particular.net/samples/azure/storage-queues/

I took the sample, ran the storage emulator and tried publishing an event. I get an error "No stage connector found for stage NServiceBus.Pipeline.IOutgoingPublishContext".

Is this a bug or is this not supported with this transport?

**Comment by ramonsmits** [comment]
@MarcusChamberlain Publish subscribe (pubsub) is supported with Azure Storage Queues, however, the transport itself doesn't support pubsub natively. It uses message drive pubsub. In order for that to work you configure a persister that implements subscription storage, the learning persister does not support this. You can use the non-durable InMemoryPersister instead.

Also, the sample disables message driven pubsub:

- https://github.com/Particular/docs.particular.net/blob/master/samples/azure/storage-queues/ASQ_8/Endpoint2/Program.cs#L21

I'm not sure why that is done in the sample as that likely causes this issue. So please remove the disabling of features and select the in memory persistence or one of the other durable persisters like NHibernate Persistence, SQL Persistence or Azure Persistence.

**Comment by SeanFeldman** [comment]
> I'm not sure why that is done in the sample as that likely causes this issue.

The sample is focusing on ASQ for send/reply, not pub/sub.
To enable pub/sub, please follow the steps @ramonsmits provided.

One tiny nit: I'd would recommend to start with [Azure Storage persistence](https://docs.particular.net/persistence/azure-storage/) first, and then evaluate other persistences if you're building an Azure-based solution.
