### ISSUE TITLE
DelayedMessagesPoller polls too often when no delayed messages are around

### ISSUE THREAD

**Issue by timbussmann** [Particular/NServiceBus.AzureStorageQueues#324]
When enabling debug level logging, you'll notice that the `DelayedMessagesPoller` reports a polling attempt multiple times per second, even when no delayed message is around. Looking at the implementation, at first glance it doesn't look like the poller is supposed to behave that way and talking to @SeanFeldman confirmed that assumption further.

This has been brought up via support case from a customer noticing the polling attempts to his storage account. I've verified this behavior using the ASQ transport sample and changing the log level to debug.

ping @Particular/azure-maintainers

**Comment by Scooletz** [comment]
Bringing some numbers to show pricey this is:

According to the [pricing of Azure Storage Queues](https://azure.microsoft.com/en-us/pricing/details/storage/queues/) querying for queues is `Operation 2` which costs (West Europe) `€0.0034` per `10000` requests. To bring some estimation, the query is done 8 times a sec

(8 * 3600 * 24) / 10000 * 0.0034 = ~0.235 Euro/day

**Comment by Scooletz** [comment]
#326 provides a fix for it

**Comment by danielmarbach** [comment]
Fixed and released as part of 7.5.4 and 8.0.1

**Comment by gcobasmegia** [comment]
Hi Daniel, 

Do we necessarily have to wait for NServiceBus 7.5.4 to apply this patch? or are we ok with just 
using NServiceBus.Azure.Transports.WindowsAzureStorageQueue 8.0.1?

**Comment by danielmarbach** [comment]
@gcobasmegia 

Sorry for the confusion. The version numbers you see above are for

NServiceBus.Azure.Transports.WindowsAzureStorageQueue 7.5.4
 NServiceBus.Azure.Transports.WindowsAzureStorageQueue 8.0.1

so if you are on 8.0.0 upgrade to 8.0.1. Does that make things clearer?

**Comment by gcobasmegia** [comment]
Yes, very clear.  Thanks a lot!
