### ISSUE TITLE
Update Storage library to the latest (9.x) and enable infinite TTL

### ISSUE THREAD

**Issue by SeanFeldman** [Particular/NServiceBus.AzureStorageQueues#325]
Version 9.x of Azure Storage library (2017-07-29 REST API) has added support for infinite TTL on queue messages.  This means the transport can support 

1. TTBR > 7 days
1. Store messages infinitely w/o the worry for loosing messages

Additionally, dependencies on OData libraries where removed, reducing footprint of this libarary.

Note: to enable infinite TTL, TTL parameter has to be specified.
```c#
await queue.AddMessageAsync(msg,timeToLive: TimeSpan.MaxValue, // infinite TTL or value of TTBR
null, new QueueRequestOptions(), new OperationContext());
```

![image](https://user-images.githubusercontent.com/1309622/42481348-2377b50c-839f-11e8-97e1-0fedc27c5c7b.png)

**Comment by danielmarbach** [comment]
Plus it contains the perf improvements we contributed

**Comment by SeanFeldman** [comment]
Infinite TTL is great, though would suggest to stick to 31 days.
To ensure there are no surprises in the future.
