### ISSUE TITLE
Raise a critical error when an exception thrown in the recoverability policy

### ISSUE THREAD

**Issue by SeanFeldman** [Particular/NServiceBus.AzureStorageQueues#358]
By not properly handling exceptions when the recoverability policy throws, and not raising a critical error, we the transport prevents from taking an action when the underlying messaging infrastructure is partially failing.

Unnecessary and misleading logging (warning) clutters the log files with exception information already logged by recoverability in Core. Log level warn downplays the significance of the accident, masquerading the transport errors.

**Comment by andreasohlund** [comment]
This is fixed in https://github.com/Particular/NServiceBus.AzureStorageQueues/issues/360, should this be closed?

**Comment by SeanFeldman** [comment]
Fixed and released.
