### ISSUE TITLE
Review 'Public' implementations

### ISSUE THREAD

**Issue by yvesgoeleven** [Particular/NServiceBus.AzureStorageQueues#43]
Connects to https://github.com/Particular/PlatformDevelopment/issues/723

In general we don't want public implementations of interfaces anymore, as people tend to abuse them over time. Please review the codebase for public implementations and make internal where possible.

**Comment by petersgiles** [comment]
I don't think this is an impediment to delivering v6. I say we leave this for v7.

@yvesgoeleven please remove v6 tag

**Comment by SeanFeldman** [comment]
@petersgiles Can I suggest first to find out how much effort is involved in this prior to making any decisions? If we're talking about days/weeks, no argument. Otherwise, let's seal it.

**Comment by petersgiles** [comment]
@SeanFeldman if you guys think its vital for v6, continue on. From the description I think it can wait. Surely it could remain as broken as it is for one more version

**Comment by yvesgoeleven** [comment]
@petersgiles this can't wait, if public classes leave into the wild they will be used and abused, meaning we can't remove them again later without pissing off customers. Better to remove the keywords before we release

**Comment by andreasohlund** [comment]
Let's add ApiApprover to ASQ to make it easier to review and make sure that we don't add more public types by misstake?

**Comment by SeanFeldman** [comment]
I've added APIApprover in PR #56 
Review of what should or should not be public still needs to take a place. APIApprover will make it easier to ensure we don't break public API moving forward.

**Comment by Scooletz** [comment]
I agree with @SeanFeldman The review as it's stated in https://github.com/Particular/NServiceBus.AzureStorageQueues/issues/43 still needs to take place.

**Comment by WojcikMike** [comment]
With my limited knowledge of Transports let me make a stub at this:

Let me first list the public types of this project:
* Public Implementations:
 * `MessageWrapper`
 * `HeadersCollection`
 * `AzureStorageQueueTransport`
* Public Classes:
 * `QueueIndividualizer`
 * `MessageWrapperSerializer`
 * `Shortener`
* Extension classes
 * `AzureStorageTransportExtensions`
 * `AzureStorageTransportAddressingExtensions`
* Exceptions:
 * `RoleEnvironmentUnavailableException`
 * `EnvelopeDeserializationFailed`
 * `UnableToDispatchException`
* Public interfaces:
 * `IAzureStoragePartitioningSettings`
 * `ICreateQueueClients`
* Other
 * `WellKnownConfigurationKeys`

**Comment by WojcikMike** [comment]
In the PR I addressed most of the above types leaving:
* MessageWrapper
* HeadersCollection
* MessageWrapperSerializer

To be done by @Scooletz

**Comment by Scooletz** [comment]
The changes mentioned by @WojcikMike have been addressed in this PR https://github.com/Particular/NServiceBus.AzureStorageQueues/pull/72 which is now waiting for a review and a merge.

**Comment by Scooletz** [comment]
PR has been merged
