### ISSUE TITLE
Bump up the core once again

### ISSUE THREAD

**Issue by Scooletz** [Particular/NServiceBus.AzureStorageQueues#47]
Connects to #22

We need to bump up the core once again as there have been changes introduced on the transport seam level.

**Comment by dvdstelt** [comment]
I'm blocked picking up this : https://github.com/Particular/ProductionTests/issues/45
So I'll do this first.

**Comment by andreasohlund** [comment]
@Particular/transport-maintainers since @Scooletz is busy with the saga persister can we hand this one over to some one else?

**Comment by dvdstelt** [comment]
This is ready for merge

**Comment by yvesgoeleven** [comment]
Merged
