### ISSUE TITLE
Microsoft.Azure.Cosmos.Table is deprecated in favor of Azure.Data.Table

### ISSUE THREAD

**Issue by SeanFeldman** [Particular/NServiceBus.AzureStorageQueues#541]
[Azure.Data.Table](https://www.nuget.org/packages/Azure.Data.Tables) is replacing the currently used [Microsoft.Azure.Cosmos.Table](https://www.nuget.org/packages/Microsoft.Azure.Cosmos.Table). It has been [announced](https://devblogs.microsoft.com/azure-sdk/azure-tables-client-libraries/) not long ago that the plan is to consolidate Table Storage and Cosmos DB Table API SDKs into one under the Azure SDK roof.

**Related issues**:
- https://github.com/Particular/NServiceBus.Persistence.AzureStorage/issues/386
- https://github.com/Particular/TimeoutMigrationTool/issues/200

**Comment by abparticular** [comment]
[MIgration guide](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/tables/Azure.Data.Tables/MigrationGuide.md)

**Comment by abparticular** [comment]
Will be shipped with release v12.0

**Comment by abparticular** [comment]
More information can be found at https://discuss.particular.net/t/nservicebus-transport-azurestoragequeues-12-0-0-major-release-available/3277
