### ISSUE TITLE
Possibly simplify setup of ASQ serializer

### ISSUE THREAD

**Issue by Scooletz** [Particular/NServiceBus.AzureStorageQueues#55]
Connects to Particular/PlatformDevelopment#723

Because of the serialization changes in the core, a serialization aspect has been introduced to the ASQ in here: https://github.com/Particular/NServiceBus.AzureStorageQueues/blob/develop/src/Transport/MessageWrapperSerializer.cs
It looks like that the accepted core `PR` https://github.com/Particular/NServiceBus/pull/3617 could change it and re-enable setting the serializer.
We need to check if it's possible. If it is, the whole code responsible for handling serialization in ASQ could be deleted.

**Comment by yvesgoeleven** [comment]
Indeed, keep an eye on that conversation and remove if needed

**Comment by andreasohlund** [comment]
Seems very resonable, removing the consider for v6 since this will go into https://github.com/Particular/PlatformDevelopment/issues/723 which currently is flagged as v6 and is in progress

**Comment by Scooletz** [comment]
Solved by  #72
