### ISSUE TITLE
Review configuration API

### ISSUE THREAD

**Issue by melkio** [Particular/NServiceBus.AzureStorageQueues#63]
Configuration API should be more similar to ASB config API, to improve users experience across Azure transports.
Namespaces have to be reviewed to make config API easily discoverable

**Comment by Scooletz** [comment]
The serializer API is covered somehow by #55 and could be reviewed with the rest of the API.

**Comment by dvdstelt** [comment]
I don't think this issue should be discussed here, but rather discussed broader. During the last couple of weeks requirements changed continuously, depending on who you'd speak with and there was no consensus on how it should work. There are/were GH issues in core, but these weren't marked for V6. We did however change everything. I didn't verify, but if we want a better user experience, we should do this across NServiceBus and actually improve user experience. Not just enforce some ideas we had and leave users in the cold with no other option than to migrate and come up with their own solution.

**Comment by melkio** [comment]
@dvdstelt issue has been raised because ASQ and ASB api config should be more consistent (where possible). I agree, the issue could spread others repos, but my focus was about `azure transports`

**Comment by Scooletz** [comment]
The serializer issue has been solved #55. @melkio, could you update the description accordingly? If we want to change the API surface still, we should do it in before beta.

**Comment by melkio** [comment]
@Scooletz updated

**Comment by Scooletz** [comment]
I've reviewed this and the differences between these two for now:

ASQ:
```
configuration.UseTransport<AzureStorageQueueTransport>()
	.Addressing()
	.Partitioning()
	.AddStorageAccount(AnotherAccountName, "sth");
```

ASB:
```
 extensions
 	.UseTopology<ForwardingTopology>()
 	.NamespacePartitioning()
 	.AddNamespace(Name, Connectionstring)
```

@Particular/azure-service-bus-maintainers please chime in. Should we align ASQ to ASB for sake of future multinamespace support?

**Comment by melkio** [comment]
(IMO) ASB and ASQ should be aligned as much as possible to guide users through transports config APIs easier

Two things in ASQ config API you pointed out:
- too much nesting. ASB config API has been flattened. 
- Why does exist method `AddStorageAccount`, that can be invoked multiple times, if transport doesn't support _multiple accounts_ (yet)?

**Comment by melkio** [comment]
Moreover:
- `AzureStorageAddressingSettings` is a mix between configuration and behavior. ASB splits clearly the two things. I'd rather this approach.
- is `IAzureStoragePartitioningSettings` useless?
- what's the purpose of `AzureStorageTransportAddressingExtensions.Partitioning` method?
- is `AzureStorageTransportExtensions.ConnectionString` useless? `TransportExtensions<T>` already exposes this method

I was working on this review when WIP limit stopped me :(
Can I start again to work on it? :)

**Comment by SeanFeldman** [comment]
:+1: @dvdstelt for noting that this should be a broader discussion.

:+1: @melkio for flattening configuration. Saying that, we've only recently made that change. So ASB is not an :innocent: 

I'll ask a different question: rather than saying X should be consistent with Y, should we ask "what are our users are doing?". Someone who's running on ASB is not going to configure ASQ and the other way around. By trying to "unify" configuration APIs, will we make it easier for a user of a specific transport to configure it? When I'm using ASQ, I know I'm dealing with *storage accounts*. When I'm working with ASB, I know I'm working with *namespaces*. So it's already different :)

**Comment by dvdstelt** [comment]
I'm with you, @SeanFeldman . It took WCF years and 3 versions to get it right and most people have no idea what to do with WCF configuration. I'd want to release v6 before that ;-)

**Comment by melkio** [comment]
I try to explain in a different way: what I'm saying isn't that a transport is better than another. What I'm trying to do is to learn from other transports and bring into ASQ good choices taken elsewhere to avoid to reinvent the wheel each time. 

@SeanFeldman agree with your point, but what I suggested wasn't to completely unify config API among transports. It's impossible. What I'm suggesting is to unify only common configuration between ASB and ASQ (in this case what I was talking about was _namespace/account mapping_)

Moreover, what about writing something like this:

```
extensions.
   .Addressing()
   .Partitioning()
   .AddStorageAccount("account1", "connectionString1");
``` 

to map a _storage account_? Too many lines of code for a "simple" configuration...

Another scenario:

```
extensions.
   .Addressing()
   .Partitioning()
       .AddStorageAccount("account1", "connectionString1");
       .UseAccountNamesInsteadOfConnectionStrings()
       .AddStorageAccount("account2", "connectionString2");
``` 

We're mixing different concerns. Confused!

I don't like so much _fluent interfaces_, but when they're well designed can be useful to help users to go through the configuration. I think ASQ config API design isn't good enough.

@dvdstelt I agree about WCF, indeed anyone is able to configure it :) 
but we can't compare WCF config complexity with ASQ config API. We can do better with our config API (IMO). 

Take a look to other points I listed in my previous comments and let me know what you think about them.

@Particular/azure-service-bus-maintainers @Particular/azure-storage-queues-maintainers

**Comment by Scooletz** [comment]
I'm considering dropping this from the beta scope. I can't provide a better API taking into consideration that [multinamespace support](https://github.com/Particular/NServiceBus.AzureStorageQueues/issues/21) will come some day. I'd more than happy to see a PR changing this if there's anything to change.
Thoughts @Particular/azure-storage-queues-maintainers ?

**Comment by timbussmann** [comment]
@Particular/azure-storage-queues-maintainers @Scooletz after a discussion today, I think we shouldn't drop this for beta. The current API is highly confusing and YAGNI. "multinamespace" support is not here yet, having some API which doesn't do anything and which is designed for a future feature is a huge smell.

I think we need to drop `Addressing()`, `Partitioning()` and `AddStorageAccount()` altogether and rename `UseAccountNamesInsteadOfConnectionStrings` to something less confusing (e.g. `DoNotIncludeConnectionStringsInOutgoingMessages` or `UseConnectionStringAlias`)
