### ISSUE TITLE
Exceptions at shutdown logged as WARN

### ISSUE THREAD

**Issue by ramonsmits** [Particular/NServiceBus.AzureStorageQueues#65]
Connects to https://github.com/Particular/PlatformDevelopment/issues/723
Getting the following exceptions during a shutdown:

> 2016-04-07 18:09:59.636 WARN  NServiceBus.Azure.Transports.WindowsAzureStorageQueues.MessagePump Receiving from the queue failed

> 2016-04-07 18:09:59.649 WARN  NServiceBus.Azure.Transports.WindowsAzureStorageQueues.RepeatedFailuresOverTimeCircuitBreaker The circuit breaker for AzureStorageQueue-MessagePump is now in the armed state

> 2016-04-07 18:09:59.657 WARN  NServiceBus.Azure.Transports.WindowsAzureStorageQueues.MessagePump Receiving from the queue failed

Cancellation should be caught and handled as this is an expected scenario.

**Comment by Scooletz** [comment]
I agree. I want to clarify the description though: 

The thrown exception does not impact functionality, the shutdown is performed properly. The exception should be handled properly though to do not clutter logs.
