### ISSUE TITLE
Upgrade Storage Library to version 7.0.0

### ISSUE THREAD

**Issue by SeanFeldman** [Particular/NServiceBus.AzureStorageQueues#66]
Connects to Particular/PlatformDevelopment#723

With version 7.0.0 of the WindowsAzure.Storage library, we should package ASQ with it to allow customers to use version 7+, which they will be asking to allow them to use the latest MSFT library.

**Comment by WojcikMike** [comment]
The latest code reference WindowsAzure.Storage 7.0.0:

https://github.com/Particular/NServiceBus.AzureStorageQueues/blob/develop/src/Transport/packages.config#L16

So I will close this issue as this is done
