### ISSUE TITLE
Get messages asynchronously

### ISSUE THREAD

**Issue by Scooletz** [Particular/NServiceBus.AzureStorageQueues#76]
Currently, `GetMessage` method uses a queue to batch messages obtained from `ASQ` for future tasks. When the queue is empty it uses an awaited call to `ASQ` obtaining a batch of messages. The messages are added to the queue and they're dispatched later on. This approach creates some friction, as once in a while it awaits for the result from the `ASQ`.
A possibly better approach, would be having a smart fetcher that would be run in a separate thread and would try to fill a concurrent queue up to the batch limit (some 'smartness' could be applied as well). `GetMessage` method would simply use 'ConcurrentQueue.TryDequeue` obtaining a message if there's anything in the queue. This behavior would result in having no need for waiting on a web request result.

**Concurrency note:** it's a single consumer single producer scenario, so a better structures than ConcurrentQueue can be used, for example http://joeduffyblog.com/2009/10/04/fast-synchronization-between-a-single-producer-and-single-consumer/ or similar

Current implementation:
```
async Task<CloudQueueMessage> GetMessage(CancellationToken token)
{
    if (batchQueue.Count == 0)
    {
        var messages = await azureQueue.GetMessagesAsync(BatchSize, TimeSpan.FromMilliseconds(MessageInvisibleTime), null, null, token).ConfigureAwait(false);
        foreach (var receivedMessage in messages)
        {
            batchQueue.Enqueue(receivedMessage);
        }
    }
    if (batchQueue.Count > 0)
    {
        return batchQueue.Dequeue();
    }

    return null;
}
```

Proposed implementation:
```
CloudQueueMessage GetMessage(CancellationToken token)
{
    CloudQueueMessage msg;
    if (concurrentBatchQueue.TryDequeue(out msg))
    {
        return msg;
    }
    return null;
}
```
Link to the method: https://github.com/Particular/NServiceBus.AzureStorageQueues/blob/develop/src/Transport/AzureMessageQueueReceiver.cs#L95

**Comment by Scooletz** [comment]
The issue we discussed @andreasohlund

**Comment by andreasohlund** [comment]
:+1:  cc @danielmarbach

**Comment by danielmarbach** [comment]
I propose we wait with this until we have more intel from the perf analysis
and profiling

**Comment by Scooletz** [comment]
This is closed because of a much better approach provided by #77
