### ISSUE TITLE
Unable to consume v5 messages from a v6 endpoint

### ISSUE THREAD

**Issue by danielmarbach** [Particular/NServiceBus.AzureStorageQueues#86]
Connects to https://github.com/Particular/PlatformDevelopment/issues/723

I was using

https://github.com/danielmarbach/Chocolate.Power
https://github.com/danielmarbach/SwissChocolate.Power

tweaked it to use ASQ with Json, started the Chocolate.Power Facility endpoint, let it produce 1000 messages and then started the SwissChocolate.Power Facility.Producer endpoint (also ASQ and JSON) to consume the messages. All ended up in the error queue. Do we have an incompatibility on the transport level?

**Comment by melkio** [comment]
Different versions of transport should be backward compatible. 
There is also a specific repo (https://github.com/Particular/EndToEnd/tree/master/src/TransportCompatibilityTests) to check compatibilites among different versions of the same transport. I wonder why tests don't fail there

You mentioned v5 vs v6 issue. Are you speaking about core versions?

**Comment by Scooletz** [comment]
The [Serializer PR](https://github.com/Particular/NServiceBus.AzureStorageQueues/pull/72) should be addressing it.

**Comment by danielmarbach** [comment]
@melkio as far as I remember those tests only test MSMQ with different core versions.

**Comment by SeanFeldman** [comment]
> I was using
> https://github.com/danielmarbach/Chocolate.Power
> https://github.com/danielmarbach/SwissChocolate.Power

Thanks @danielmarbach, all I can hear now is [this](https://www.youtube.com/watch?v=_BRv9wGf5pk) :)

**Comment by Scooletz** [comment]
@danielmarbach Could you rerun the tests with `develop` version? The serializer PR has been merged.

**Comment by danielmarbach** [comment]
Will do

**Comment by melkio** [comment]
No @danielmarbach I added `RabbitMQ` backward compatibility tests months ago. 
Repo contains tests against `SqlServer`, `RabbitMQ`, `ASB` and `ASQ` transports

**Comment by Scooletz** [comment]
Closed as #100 is merged
