### ISSUE TITLE
does CreateQueueClients need a cache

### ISSUE THREAD

**Issue by SimonCropp** [Particular/NServiceBus.AzureStorageQueues#88]
Connects to https://github.com/Particular/PlatformDevelopment/issues/723

so `CreateQueueClients` has an instance based cache field `destinationQueueClients`. But the only two usages of `CreateQueueClients` new up an instance, negating any value of the cache. So is the cache still required?

**Comment by Scooletz** [comment]
The cache is static. It will be preserved across instances.

**Comment by SimonCropp** [comment]
@Scooletz  cache is static?  https://github.com/Particular/NServiceBus.AzureStorageQueues/blob/develop/src/Transport/CreateQueueClients.cs#L30

**Comment by Scooletz** [comment]
I'm sorry, it isn't. I don't know what I was looking at. I'll move this to the scope of beta.

**Comment by timbussmann** [comment]
this cache is passed and used by the `Dispatcher` which is a Singleton. Concurrent dispatches may use that cache, so I think it's still required?

**Comment by danielmarbach** [comment]
We changed it to be no longer static since the instance is used for the dispatcher which is a singleton. The effect is that we can reuse queue client. The performance impact is visible as @timbussmann and I tested

**Comment by Scooletz** [comment]
Update to this: the cache is used by the dispatcher when sending messages to parse the connection string and create the client only once. Its beneficial to use the same instance of the client. The dictionary is used for cases where sends are performed across different accounts.
The dispatched itself is constructed only once, hence the cache will ensure proper behavior.

Does it clarify doubts?

**Comment by Scooletz** [comment]
@SimonCropp Are you ok with the explanation above?

**Comment by SimonCropp** [comment]
groked. closing
