### ISSUE TITLE
purpose of IAzureStoragePartitioningSettings?

### ISSUE THREAD

**Issue by SimonCropp** [Particular/NServiceBus.AzureStorageQueues#95]
it only has one implementation. and i see no way passing an instance into the api. and the only time it is exposed an instance of AzureStorageAddressingSettings is returned

**Comment by melkio** [comment]
@SimonCropp : take a look here :) https://github.com/Particular/NServiceBus.AzureStorageQueues/issues/63#issuecomment-213562783
