### ISSUE TITLE
AzureMessageQueueCreator.CreateQueueIfNecessary should not await

### ISSUE THREAD

**Issue by SimonCropp** [Particular/NServiceBus.AzureStorageQueues#96]
Since this 

        public async Task CreateQueueIfNecessary(QueueBindings queueBindings, string identity)
        {
            var addresses = queueBindings.ReceivingAddresses.Union(queueBindings.SendingAddresses).ToArray();

            await Task.WhenAll(addresses.Select(CreateQueue)).ConfigureAwait(false);
        }

has only one await it should return the task directly. so as to avoid an extra state machine

        public Task CreateQueueIfNecessary(QueueBindings queueBindings, string identity)
        {
            var addresses = queueBindings.ReceivingAddresses.Union(queueBindings.SendingAddresses).ToArray();

            return Task.WhenAll(addresses.Select(CreateQueue));
        }

**Comment by SimonCropp** [comment]
@danielmarbach the above is correct?

**Comment by SimonCropp** [comment]
same goes for `AzureMessageQueueCreator.CreateQueue`

**Comment by danielmarbach** [comment]
Correct! Good find

**Comment by SimonCropp** [comment]
@distantcam can this be detected in roslyn? and possible to put it in coderules?
