### ISSUE TITLE
Consider throwing an exception instead of hashing queues names

### ISSUE THREAD

**Issue by Scooletz** [Particular/NServiceBus.AzureStorageQueues#99]
> i know there is a lot of legacy. but the difficulty in debugging hashed queue names makes me think we should deprecate it and throw an exception at startup for long queue names. they can always work around by hashing themselves

By @SimonCropp in https://github.com/Particular/docs.particular.net/pull/1439#discussion_r60722317

**Comment by SeanFeldman** [comment]
This is not ASQ specific https://github.com/Particular/docs.particular.net/pull/1439#discussion_r60813426

**Comment by Scooletz** [comment]
I'm closing it then.

**Comment by SeanFeldman** [comment]
@Particular/azure-storage-queues-maintainers 

After discussions with @SimonCropp and @yvesgoeleven about the same issue in ASB, we've decided that we shouldn't take upon ourselves the responsibility to manage the hashing algorithm beyond MD5 for backward compatibility. An exception should be thrown for invalid queue names. To support older version, a backward compatible option could be provided with the transport. As well a way to register a custom Sanitization strategy.

Reopening this issue for ASQ to review if the same approach should be taken.

**Comment by dvdstelt** [comment]
Loving this! As a customer I would be really, really surprised when queue names popped up, of which I had no idea who created them.

**Comment by Scooletz** [comment]
@dvdstelt The name would have the same 30 character long prefix as the original name. It's not full name but can give you at least some knowledge what's the reason for creating it.

**Comment by Scooletz** [comment]
@SeanFeldman Currently we support `MD5` & `SHA1`. Would you like to create another option to support `ThrowOnQueueToLong` or drop the support for hashing at all?
The second question is do you want to include it in the current beta for ASB?

**Comment by dvdstelt** [comment]
@Scooletz If it's already that long, it's probably because of naming conventions with a really, really long prefix.

`MyCompanyWithLongName.MyDepartmentWithLongName.MyBoundedContextWithLongName.MyBusinessComponentWIthLongName.MyAutonomousComponentWithLongName`

would become

`MyCompanyWithLongName.MyDepar_a175ec0c3e17a8451e4b8e97bbe26e67`

or something like it? So with 50 queues, it's 50 times the prefix and something hashed, making all of them unrecognizable. I prefer these things to be explicit and throwing an exception is definitely explicit. So I'm all for throwing.

I'm all for providing the option though, but not as default. Make the choice explicit!

**Comment by SeanFeldman** [comment]
For SB we've decided to go with the following:
1. By default, throw an exception if names violate the length or allowed characters.
2. Provide an option for MD5 to be backward compatible and document how to use it.
3. For SHA1 provide a sample if needed.

**Comment by Scooletz** [comment]
@dvdstelt Point taken :)

**Comment by Scooletz** [comment]
@SeanFeldman That looks reasonable to me. My thinking about this lead me to awkward ways of providing this API. An explicit choice for one of the following looks like perfect API for this. Could you provide a link to ASB API in here, to keep it aligned?

**Comment by SeanFeldman** [comment]
* [Configuration API](https://github.com/Particular/NServiceBus.AzureServiceBus/blob/a6c0341ac12e1c39875e6de96977f9fd40789efa/src/Transport/Config/ExtensionPoints/AzureServiceBusSanitizationSettings.cs)
 * [Backwards compatibility OOTB](https://github.com/Particular/NServiceBus.AzureServiceBus/blob/a6c0341ac12e1c39875e6de96977f9fd40789efa/src%2FAcceptanceTests%2FConfigureEndpointAzureServiceBusTransport.cs#L67) 
 * Doco and sample for custom strategy are a wip

**Comment by tmasternak** [comment]
What is the estimated time to make this change?

**Comment by Scooletz** [comment]
@tmasternak I'd say 2-3 days including doco.

**Comment by yvesgoeleven** [comment]
Closing as it has been finished (long time ago)
